{
  "hash": "fe09c42bd1d52b6455ef4fb42cabe265",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Búsquedas programáticas en Interpro\"\nlang: es\ndate: today\nexecute: \n  output: true\n  error: true\nengine: knitr\nbibliography: ../../doc/references.bib\nlanguage:\n   title-block-published: \"Última actualización:\"\n   section-title-references: \"Bibliografía\"\nformat:\n   html:\n      embed-resources: true\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n# PRÁCTICA 6\n\n## Objetivos\n\n1.  Aprender a usar la API de\n    [Interpro](https://www.ebi.ac.uk/interpro/).\n2.  Recordar que existen las herramientas `datasets` y `dataformat` de\n    [NCBI](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/).\n\n## Introducción\n\nTodas las consultas a InterPro [@Paysan-Lafosse2022] deben empezar con\nla dirección de la API: `https://www.ebi.ac.uk/interpro/api/`\n[@interproAPI]. Por tanto, guardo esta URL básica como cadena de\ncaracteres en la variable `API`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAPI <- 'https://www.ebi.ac.uk/interpro/api/'\n```\n:::\n\n\n\n\nLa API devuelve los datos en un formato llamado JSON, basado en texto\nplano. Necesitamos un paquete que nos ayude a leer los archivos JSON.\nPor ejemplo, `jsonlite` [@jsonlite]:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary('jsonlite')\n```\n:::\n\n\n\n\n## Contar registros\n\nEn InterPro existen seis tipos principales de datos:\n\n-   *Entry*: elementos funcionales predichos sobre las proteínas. Se\n    pueden distinguir los definidos por cada base de datos: InterPro,\n    Pfam, CDD, etc.\n-   *Protein*: las secuencias proteicas procedentes de UniProtKB. Pueden\n    ser *reviewed* (Swiss-Prot) o *unreviewed* (TrEMBL).\n-   *Taxonomy*: Organismo y su linaje del que proviene una proteína. La\n    fuente de estos datos es UniProtKB.\n-   *Structure*: Estructuras tridimensionales de las proteínas.\n    Proporcionadas por la base de datos PDB.\n-   *Set*: Conjuntos de registros (*entries*) relacionados, de acuerdo\n    con las bases de datos Pfam o CDD.\n-   *Proteome*: Conjuntos de proteínas de un mismo organismo.\n    Proporcionados por UniProtKB.\n\nPodemos consultar el número de registros de tipo *entry* en la URL\n`https://www.ebi.ac.uk/interpro/api/entry`, cuyo contenido se muestra\naquí:\n\n```         \n{\n    \"entries\": {\n        \"member_databases\": {\n            \"pfam\": 25501,\n            \"cathgene3d\": 6566,\n            \"ssf\": 2019,\n            \"panther\": 15912,\n            \"cdd\": 19760,\n            \"profile\": 1399,\n            \"smart\": 1322,\n            \"ncbifam\": 32088,\n            \"prosite\": 1311,\n            \"prints\": 2106,\n            \"hamap\": 2391,\n            \"pirsf\": 3292,\n            \"sfld\": 303,\n            \"antifam\": 278\n        },\n        \"integrated\": 62376,\n        \"unintegrated\": 52549,\n        \"interpro\": 49900,\n        \"all\": 165723\n    }\n}\n```\n\nLa función `fromJSON` del paquete `jsonlite` nos permite guardar este\ntipo de datos en una lista de listas. En R, podemos acceder a los\nelementos de una lista con la función *doble corchete* `[[`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregistros <- fromJSON(paste0(API, 'entry'))\nregistros[[1]][['member_databases']]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$pfam\n[1] 27208\n\n$cathgene3d\n[1] 6566\n\n$ssf\n[1] 2019\n\n$panther\n[1] 15912\n\n$cdd\n[1] 19760\n\n$profile\n[1] 1399\n\n$smart\n[1] 1322\n\n$ncbifam\n[1] 33921\n\n$prosite\n[1] 1311\n\n$prints\n[1] 2106\n\n$hamap\n[1] 2391\n\n$pirsf\n[1] 3292\n\n$sfld\n[1] 303\n\n$antifam\n[1] 278\n```\n\n\n:::\n:::\n\n\n\n\n### Ejercicio 1\n\n*Construye las URLs necesarias para determinar el número de registros\ndel resto de tipos: protein, structure, set, y proteome. Fíjate en las\nposibles fuentes de cada tipo de datos, e intenta guardar la información\nen variables de tu sesión de R.*\n\nPara cada caso:\n\n-   https://www.ebi.ac.uk/interpro/api/protein\n\n-   https://www.ebi.ac.uk/interpro/api/structure\n\n-   https://www.ebi.ac.uk/interpro/api/set\n\n-   https://www.ebi.ac.uk/interpro/api/proteome\n\nPara proteína:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproteina <- fromJSON(paste0(API, 'protein')) \nstructure <- fromJSON(paste0(API, 'structure')) \nset <- fromJSON(paste0(API, 'set')) \nproteome <- fromJSON(paste0(API, 'proteome'))\n```\n:::\n\n\n\n\n## Lista de datos de algún tipo\n\nSi además del tipo de datos (*entry*, *protein*, *taxonomy*...),\nañadimos a la URL la *fuente* o base de datos de origen que queremos\nconsultar, obtendremos la lista (completa?) de los registros de ese tipo\nprovenientes de *esa* base de datos. Consulta los ejemplos siguientes:\n\n-   https://www.ebi.ac.uk/interpro/api/entry/interpro\n-   https://www.ebi.ac.uk/interpro/api/entry/pfam\n-   https://www.ebi.ac.uk/interpro/api/protein/reviewed\n-   https://www.ebi.ac.uk/interpro/api/taxonomy/uniprot\n\nPero, para no saturar los servidores, InterPro sólo devuelve los 20\nprimeros registros de cada consulta, y ofrece una nueva URL (*next*)\npara poder ver o descargar los 20 siguientes.\n\nA continuación, usamos la función `fromJSON()` de `jsonlite` para\ndescargar los 20 primeros registros de tipo Pfam y exploramos el\nresultado.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npfam01 <- fromJSON(paste0(API, 'entry/pfam'))\nclass(pfam01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"list\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(pfam01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(pfam01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"count\"    \"next\"     \"previous\" \"results\" \n```\n\n\n:::\n\n```{.r .cell-code}\npfam01[['count']]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27481\n```\n\n\n:::\n\n```{.r .cell-code}\npfam01[['next']]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"https://www.ebi.ac.uk/interpro/api/entry/pfam/?cursor=cD1QRjAwMDIw\"\n```\n\n\n:::\n\n```{.r .cell-code}\npfam01[['previous']]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\npfam01[['results']]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   metadata.accession\n1             PF00001\n2             PF00002\n3             PF00003\n4             PF00004\n5             PF00005\n6             PF00006\n7             PF00007\n8             PF00008\n9             PF00009\n10            PF00010\n11            PF00011\n12            PF00012\n13            PF00013\n14            PF00014\n15            PF00015\n16            PF00016\n17            PF00017\n18            PF00018\n19            PF00019\n20            PF00020\n                                                     metadata.name\n1                      7 transmembrane receptor (rhodopsin family)\n2                       7 transmembrane receptor (Secretin family)\n3                   7 transmembrane sweet-taste receptor of 3 GCPR\n4  ATPase family associated with various cellular activities (AAA)\n5                                                  ABC transporter\n6        ATP synthase alpha/beta family, nucleotide-binding domain\n7                                              Cystine-knot domain\n8                                                  EGF-like domain\n9                          Elongation factor Tu GTP binding domain\n10                             Helix-loop-helix DNA-binding domain\n11                                   Hsp20/alpha crystallin family\n12                                                   Hsp70 protein\n13                                                       KH domain\n14               Kunitz/Bovine pancreatic trypsin inhibitor domain\n15     Methyl-accepting chemotaxis protein (MCP) signalling domain\n16 Ribulose bisphosphate carboxylase large chain, catalytic domain\n17                                                      SH2 domain\n18                                                      SH3 domain\n19                     Transforming growth factor beta like domain\n20                                  TNFR/NGFR cysteine-rich region\n   metadata.source_database metadata.type metadata.integrated\n1                      pfam        domain           IPR000276\n2                      pfam        domain           IPR000832\n3                      pfam        domain           IPR017978\n4                      pfam        domain           IPR003959\n5                      pfam        domain           IPR003439\n6                      pfam        domain           IPR000194\n7                      pfam        domain           IPR006208\n8                      pfam        domain           IPR000742\n9                      pfam        domain           IPR000795\n10                     pfam        domain           IPR011598\n11                     pfam        domain           IPR002068\n12                     pfam        family           IPR013126\n13                     pfam        domain           IPR004088\n14                     pfam        domain           IPR002223\n15                     pfam        family           IPR004089\n16                     pfam        domain           IPR000685\n17                     pfam        domain           IPR000980\n18                     pfam        domain           IPR001452\n19                     pfam        domain           IPR001839\n20                     pfam        domain           IPR001368\n   metadata.member_databases metadata.go_terms\n1                         NA                NA\n2                         NA                NA\n3                         NA                NA\n4                         NA                NA\n5                         NA                NA\n6                         NA                NA\n7                         NA                NA\n8                         NA                NA\n9                         NA                NA\n10                        NA                NA\n11                        NA                NA\n12                        NA                NA\n13                        NA                NA\n14                        NA                NA\n15                        NA                NA\n16                        NA                NA\n17                        NA                NA\n18                        NA                NA\n19                        NA                NA\n20                        NA                NA\n```\n\n\n:::\n\n```{.r .cell-code}\npfam01[['results']][['metadata']]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   accession                                                            name\n1    PF00001                     7 transmembrane receptor (rhodopsin family)\n2    PF00002                      7 transmembrane receptor (Secretin family)\n3    PF00003                  7 transmembrane sweet-taste receptor of 3 GCPR\n4    PF00004 ATPase family associated with various cellular activities (AAA)\n5    PF00005                                                 ABC transporter\n6    PF00006       ATP synthase alpha/beta family, nucleotide-binding domain\n7    PF00007                                             Cystine-knot domain\n8    PF00008                                                 EGF-like domain\n9    PF00009                         Elongation factor Tu GTP binding domain\n10   PF00010                             Helix-loop-helix DNA-binding domain\n11   PF00011                                   Hsp20/alpha crystallin family\n12   PF00012                                                   Hsp70 protein\n13   PF00013                                                       KH domain\n14   PF00014               Kunitz/Bovine pancreatic trypsin inhibitor domain\n15   PF00015     Methyl-accepting chemotaxis protein (MCP) signalling domain\n16   PF00016 Ribulose bisphosphate carboxylase large chain, catalytic domain\n17   PF00017                                                      SH2 domain\n18   PF00018                                                      SH3 domain\n19   PF00019                     Transforming growth factor beta like domain\n20   PF00020                                  TNFR/NGFR cysteine-rich region\n   source_database   type integrated member_databases go_terms\n1             pfam domain  IPR000276               NA       NA\n2             pfam domain  IPR000832               NA       NA\n3             pfam domain  IPR017978               NA       NA\n4             pfam domain  IPR003959               NA       NA\n5             pfam domain  IPR003439               NA       NA\n6             pfam domain  IPR000194               NA       NA\n7             pfam domain  IPR006208               NA       NA\n8             pfam domain  IPR000742               NA       NA\n9             pfam domain  IPR000795               NA       NA\n10            pfam domain  IPR011598               NA       NA\n11            pfam domain  IPR002068               NA       NA\n12            pfam family  IPR013126               NA       NA\n13            pfam domain  IPR004088               NA       NA\n14            pfam domain  IPR002223               NA       NA\n15            pfam family  IPR004089               NA       NA\n16            pfam domain  IPR000685               NA       NA\n17            pfam domain  IPR000980               NA       NA\n18            pfam domain  IPR001452               NA       NA\n19            pfam domain  IPR001839               NA       NA\n20            pfam domain  IPR001368               NA       NA\n```\n\n\n:::\n:::\n\n\n\n\nLos siguientes 20 registros de Pfam se encuentran en `pfam01[['next']]`:\nhttps://www.ebi.ac.uk/interpro/api/entry/pfam/?cursor=cD1QRjAwMDIw. Y los podemos descargar igual.\n\n**Nota:** No me deja instalarme el paquete \"kableExtra\", asi que\nsustituyo por \"knitr\".\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary('knitr')\npfam02 <- fromJSON(pfam01[['next']])\nkable(pfam02[['results']][['metadata']])\n```\n\n::: {.cell-output-display}\n\n\n|accession |name                              |source_database |type        |integrated |member_databases |go_terms |\n|:---------|:---------------------------------|:---------------|:-----------|:----------|:----------------|:--------|\n|PF00021   |u-PAR/Ly-6 domain                 |pfam            |domain      |IPR016054  |NA               |NA       |\n|PF00022   |Actin                             |pfam            |family      |IPR004000  |NA               |NA       |\n|PF00023   |Ankyrin repeat                    |pfam            |repeat      |IPR002110  |NA               |NA       |\n|PF00024   |PAN domain                        |pfam            |domain      |IPR003609  |NA               |NA       |\n|PF00025   |ADP-ribosylation factor family    |pfam            |domain      |IPR006689  |NA               |NA       |\n|PF00026   |Eukaryotic aspartyl protease      |pfam            |domain      |IPR033121  |NA               |NA       |\n|PF00027   |Cyclic nucleotide-binding domain  |pfam            |domain      |IPR000595  |NA               |NA       |\n|PF00028   |Cadherin domain                   |pfam            |domain      |IPR002126  |NA               |NA       |\n|PF00029   |Connexin                          |pfam            |domain      |IPR013092  |NA               |NA       |\n|PF00030   |Beta/Gamma crystallin             |pfam            |domain      |IPR001064  |NA               |NA       |\n|PF00031   |Cystatin domain                   |pfam            |domain      |IPR000010  |NA               |NA       |\n|PF00032   |Cytochrome b(C-terminal)/b6/petD  |pfam            |domain      |IPR005798  |NA               |NA       |\n|PF00033   |Cytochrome b/b6/petB              |pfam            |domain      |IPR005797  |NA               |NA       |\n|PF00034   |Cytochrome c                      |pfam            |domain      |IPR009056  |NA               |NA       |\n|PF00035   |Double-stranded RNA binding motif |pfam            |domain      |IPR014720  |NA               |NA       |\n|PF00036   |EF hand domain                    |pfam            |domain      |IPR002048  |NA               |NA       |\n|PF00037   |4Fe-4S binding domain             |pfam            |domain      |IPR017896  |NA               |NA       |\n|PF00038   |Intermediate filament protein     |pfam            |coiled_coil |IPR039008  |NA               |NA       |\n|PF00039   |Fibronectin type I domain         |pfam            |domain      |IPR000083  |NA               |NA       |\n|PF00040   |Fibronectin type II domain        |pfam            |domain      |IPR000562  |NA               |NA       |\n\n\n:::\n:::\n\n\n\n\n## Ejercicio 2\n\n*Crea una tercera lista con los contenidos de la tercera página de\nregistros de Pfam.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary('knitr') \nlibrary('jsonlite')\npfam03 <- fromJSON(pfam02[['next']]) \nkable(pfam03[['results']][['metadata']])\n```\n\n::: {.cell-output-display}\n\n\n|accession |name                                                         |source_database |type   |integrated |member_databases |go_terms |\n|:---------|:------------------------------------------------------------|:---------------|:------|:----------|:----------------|:--------|\n|PF00041   |Fibronectin type III domain                                  |pfam            |domain |IPR003961  |NA               |NA       |\n|PF00042   |Globin                                                       |pfam            |domain |IPR000971  |NA               |NA       |\n|PF00043   |Glutathione S-transferase, C-terminal domain                 |pfam            |domain |IPR004046  |NA               |NA       |\n|PF00044   |Glyceraldehyde 3-phosphate dehydrogenase, NAD binding domain |pfam            |domain |IPR020828  |NA               |NA       |\n|PF00045   |Hemopexin                                                    |pfam            |repeat |IPR018487  |NA               |NA       |\n|PF00046   |Homeodomain                                                  |pfam            |domain |IPR001356  |NA               |NA       |\n|PF00047   |Immunoglobulin domain                                        |pfam            |domain |IPR013151  |NA               |NA       |\n|PF00048   |Small cytokines (intecrine/chemokine), interleukin-8 like    |pfam            |domain |IPR001811  |NA               |NA       |\n|PF00049   |Insulin/IGF/Relaxin family                                   |pfam            |domain |IPR016179  |NA               |NA       |\n|PF00050   |Kazal-type serine protease inhibitor domain                  |pfam            |domain |IPR002350  |NA               |NA       |\n|PF00051   |Kringle domain                                               |pfam            |domain |IPR000001  |NA               |NA       |\n|PF00052   |Laminin B (Domain IV)                                        |pfam            |domain |IPR000034  |NA               |NA       |\n|PF00053   |Laminin EGF domain                                           |pfam            |domain |IPR002049  |NA               |NA       |\n|PF00054   |Laminin G domain                                             |pfam            |domain |IPR001791  |NA               |NA       |\n|PF00055   |Laminin N-terminal (Domain VI)                               |pfam            |domain |IPR008211  |NA               |NA       |\n|PF00056   |lactate/malate dehydrogenase, NAD binding domain             |pfam            |domain |IPR001236  |NA               |NA       |\n|PF00057   |Low-density lipoprotein receptor domain class A              |pfam            |repeat |IPR002172  |NA               |NA       |\n|PF00058   |Low-density lipoprotein receptor repeat class B              |pfam            |repeat |IPR000033  |NA               |NA       |\n|PF00059   |Lectin C-type domain                                         |pfam            |domain |IPR001304  |NA               |NA       |\n|PF00060   |Ligand-gated ion channel                                     |pfam            |family |IPR001320  |NA               |NA       |\n\n\n:::\n:::\n\n\n\n\n## Unión de *páginas* en un mismo *data frame*\n\nEl paquete `jsonlite` nos ofrece la función `rbind_pages()` para juntar\nuna lista de *data frames* en uno solo:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npfam <- rbind_pages(list(pfam01[['results']][['metadata']],\n                         pfam02[['results']][['metadata']]))\n```\n:::\n\n\n\n\nPero para leer y descargar todas las páginas, necesitaríamos alguna\nmanera de automatizar el proceso. En el Apéndice 2 encontrarás una\nsolución posible.\n\n## Mostrar todos los detalles de un registro concreto\n\nYa sabemos cómo mostrar el número de registros de un tipo y cómo\ndescargar la lista de todos ellos (de 20 en 20). El siguiente paso es\ndescargar toda la información relativa a un registro concreto, del cual\ndebemos saber su identificador. Por ejemplo, el dominio PF06235 de Pfam.\nPara ello, añadimos un tercer campo a la URL, después del tipo de datos\ny del nombre de la base de datos de procedencia: el identificador del\nregistro que queremos descargar:\n\nhttps://www.ebi.ac.uk/interpro/api/entry/pfam/PF06235\n\nLa función genérica `str()` de R nos describe la estructura de cualquier\nobjeto en R, y nos puede ayudar a entender cómo podemos acceder a cada\ndato del registro:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npf06235 <- fromJSON(paste0(API, 'entry/pfam/PF06235'))\nstr(pf06235)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 1\n $ metadata:List of 21\n  ..$ accession               : chr \"PF06235\"\n  ..$ entry_id                : NULL\n  ..$ type                    : chr \"family\"\n  ..$ go_terms                : NULL\n  ..$ source_database         : chr \"pfam\"\n  ..$ member_databases        : NULL\n  ..$ integrated              : chr \"IPR009356\"\n  ..$ hierarchy               : NULL\n  ..$ name                    :List of 2\n  .. ..$ name : chr \"NADH dehydrogenase subunit 4L (NAD4L)\"\n  .. ..$ short: chr \"NAD4L\"\n  ..$ description             :'data.frame':\t1 obs. of  4 variables:\n  .. ..$ text   : chr \"<p>This family consists of NADH dehydrogenase subunit 4L (NAD4L) proteins from the mitochondria of several para\"| __truncated__\n  .. ..$ llm    : logi FALSE\n  .. ..$ checked: logi FALSE\n  .. ..$ updated: logi FALSE\n  ..$ wikipedia               : NULL\n  ..$ literature              : NULL\n  ..$ set_info                : NULL\n  ..$ overlaps_with           : NULL\n  ..$ counters                :List of 11\n  .. ..$ subfamilies         : int 0\n  .. ..$ domain_architectures: int 3\n  .. ..$ interactions        : int 0\n  .. ..$ matches             : int 402\n  .. ..$ pathways            : int 0\n  .. ..$ proteins            : int 402\n  .. ..$ proteomes           : int 8\n  .. ..$ sets                : int 0\n  .. ..$ structural_models   :List of 2\n  .. .. ..$ alphafold: int 401\n  .. .. ..$ bfvd     : int 0\n  .. ..$ structures          : int 0\n  .. ..$ taxa                : int 645\n  ..$ entry_annotations       :List of 4\n  .. ..$ hmm           : int 0\n  .. ..$ logo          : int 0\n  .. ..$ alignment:seed: int 12\n  .. ..$ alignment:full: int 9\n  ..$ cross_references        : Named list()\n  ..$ is_llm                  : logi FALSE\n  ..$ is_reviewed_llm         : logi FALSE\n  ..$ is_updated_llm          : logi FALSE\n  ..$ representative_structure: NULL\n```\n\n\n:::\n\n```{.r .cell-code}\nnombre_largo <- pf06235[['metadata']][['name']][['name']]\nnombre_largo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"NADH dehydrogenase subunit 4L (NAD4L)\"\n```\n\n\n:::\n:::\n\n\n\n\nObtenemos lo siguiente al ejecutar este bloque: \"[NADH dehydrogenase\nsubunit 4L (NAD4L)]{.underline}\"\n\n### Ejercicio 3\n\n*Usa la función `fromJSON()` para guardar la información del registro\nP01923 (proteína de Swiss-Prot) y explora la estructura de los datos con\nla función `str()`. ¿Puedes extraer la secuencia?*\n\nSiguiendo la misma estructura del comando anterior, lo hago para P01923:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np01923 <- fromJSON(paste0(API, 'protein/reviewed/P01923')) \nstr(p01923) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 1\n $ metadata:List of 17\n  ..$ accession       : chr \"P01923\"\n  ..$ id              : chr \"HBA_GORGO\"\n  ..$ source_organism :List of 3\n  .. ..$ taxId         : chr \"9595\"\n  .. ..$ scientificName: chr \"Gorilla gorilla gorilla\"\n  .. ..$ fullName      : chr \"Gorilla gorilla gorilla (Western lowland gorilla)\"\n  ..$ name            : chr \"Hemoglobin subunit alpha\"\n  ..$ description     : chr [1:2] \"Involved in oxygen transport from the lung to the various peripheral tissues\" \"Hemopressin acts as an antagonist peptide of the cannabinoid receptor CNR1. Hemopressin-binding efficiently blo\"| __truncated__\n  ..$ length          : int 141\n  ..$ sequence        : chr \"VLSPADKTNVKAAWGKVGAHAGDYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAA\"| __truncated__\n  ..$ proteome        : chr \"UP000001519\"\n  ..$ gene            : chr \"HBA\"\n  ..$ go_terms        :'data.frame':\t5 obs. of  3 variables:\n  .. ..$ identifier: chr [1:5] \"GO:0019825\" \"GO:0020037\" \"GO:0015671\" \"GO:0005833\" ...\n  .. ..$ name      : chr [1:5] \"oxygen binding\" \"heme binding\" \"oxygen transport\" \"hemoglobin complex\" ...\n  .. ..$ category  :'data.frame':\t5 obs. of  2 variables:\n  .. .. ..$ code: chr [1:5] \"F\" \"F\" \"P\" \"C\" ...\n  .. .. ..$ name: chr [1:5] \"molecular_function\" \"molecular_function\" \"biological_process\" \"cellular_component\" ...\n  ..$ protein_evidence: int 1\n  ..$ source_database : chr \"reviewed\"\n  ..$ is_fragment     : logi FALSE\n  ..$ in_alphafold    : logi TRUE\n  ..$ in_bfvd         : logi FALSE\n  ..$ ida_accession   : chr \"479f10f36c30dd70c041c861502b6b89292a259d\"\n  ..$ counters        :List of 11\n  .. ..$ domain_architectures: int 26315\n  .. ..$ entries             : int 14\n  .. ..$ isoforms            : int 0\n  .. ..$ proteomes           : int 1\n  .. ..$ sets                : int 2\n  .. ..$ structures          : int 0\n  .. ..$ taxa                : int 1\n  .. ..$ dbEntries           :List of 8\n  .. .. ..$ cathgene3d: int 1\n  .. .. ..$ profile   : int 1\n  .. .. ..$ ssf       : int 1\n  .. .. ..$ cdd       : int 1\n  .. .. ..$ pfam      : int 1\n  .. .. ..$ panther   : int 1\n  .. .. ..$ prints    : int 2\n  .. .. ..$ interpro  : int 6\n  .. ..$ proteome            : int 1\n  .. ..$ taxonomy            : int 1\n  .. ..$ similar_proteins    : int 26315\n```\n\n\n:::\n\n```{.r .cell-code}\nsecuencia <- p01923[['metadata']][['sequence']] \nsecuencia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"VLSPADKTNVKAAWGKVGAHAGDYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR\"\n```\n\n\n:::\n:::\n\n\n\n\nLa secuencia extraída es la\nsiguiente:\"VLSPADKTNVKAAWGKVGAHAGDYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR\"\n\n## Filtros. Cruzar dos tipos de datos\n\nHasta ahora hemos construido una URL con hasta tres elementos: el tipo\nde datos, la base de datos de procedencia, y el identificador concreto.\nEstos tres elementos constituyen el *bloque de punto final* de la URL.\nTambién hemos visto que InterPro devuelve una estructura de datos\ndiferente en función de cuantos de esos tres elementos usamos (sólo el\ntipo de datos es obligatorio): un recuento de registros, una lista de\nregistros, o toda la información de un registro concreto.\n\nSi al *bloque de punto final* añadimos un segundo tipo de datos,\nobtendremos un recuento o una lista del primer tipo de datos con\ninformación sobre el segundo. Por ejemplo, al comparar estas 2 URLs:\n\n-   https://www.ebi.ac.uk/interpro/api/protein\n-   https://www.ebi.ac.uk/interpro/api/protein/entry\n\npodemos observar que no en todas las proteínas en UniProtKB se encuentra\nalgún dominio o elemento funcional en InterPro.\n\n### Ejercicio 4\n\n*Determina cuántos taxones de UniProtKB no tienen ninguna proteína\nasignada. ¿Y qué proporción de proteínas cuentan con una estructura\nterciaria?*\n\nAhora usamos la taxonomía, cuyos datos provienen de UniProtKB.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntaxonomy <- fromJSON(paste0(API,'taxonomy')) \ntaxonomyprotein <- fromJSON(paste0(API, 'taxonomy/protein')) \nstr(taxonomy) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 1\n $ taxa:List of 1\n  ..$ uniprot: int 2678841\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(taxonomyprotein)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 2\n $ taxa    :List of 1\n  ..$ uniprot: int 1291419\n $ proteins:List of 3\n  ..$ unreviewed: int 201794580\n  ..$ reviewed  : int 571702\n  ..$ uniprot   : int 202150435\n```\n\n\n:::\n\n```{.r .cell-code}\ntaxones_total <- taxonomy[['taxa']][['uniprot']]-taxonomyprotein[['taxa']][['uniprot']] \ntaxones_total \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1387422\n```\n\n\n:::\n:::\n\n\n\n\nPor tanto, el número total de taxones que no tienen proteína asignada es\nde 1387422.\n\nAhora siguiendo los mismos pasos lo hacemos pero para la estructura\nterciaria, usando \"structure\" en vez de \"taxonomy\".\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprotein <- fromJSON(paste0(API,'protein')) \nproteinstructure <- fromJSON(paste0(API, 'protein/structure')) \nstr(protein) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 1\n $ proteins:List of 3\n  ..$ unreviewed: int 201794580\n  ..$ reviewed  : int 571702\n  ..$ uniprot   : int 202150435\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(proteinstructure) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 2\n $ proteins  :List of 3\n  ..$ reviewed  : int 37334\n  ..$ unreviewed: int 30128\n  ..$ uniprot   : int 67874\n $ structures:List of 1\n  ..$ pdb: int 228088\n```\n\n\n:::\n\n```{.r .cell-code}\nprot3d <- protein[['proteins']][['uniprot']]\nproteinstructure[['proteins']][['uniprot']] \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67874\n```\n\n\n:::\n\n```{.r .cell-code}\nprot3d\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 202150435\n```\n\n\n:::\n:::\n\n\n\n\nEl número total de estructuras primarias es de 202082561. Mientras que\n67874 es el número total de estructuras tridimensionales.\n\n**Nota:** he usado proteins = tanto reviewed como unreviewed.\n\n## Filtros. Subconjunto de registros\n\nPodemos especificar un registro concreto de un tipo de datos para\nlimitar una lista de registros de otro tipo de datos. Por ejemplo, la\nlista de proteínas de la base de datos *reviewed* (Swiss-Prot) anotadas\ncon la familia Pfam PF00019 (*Transforming grow factor beta like\ndomain*):\n\nhttps://www.ebi.ac.uk/interpro/api/protein/reviewed/entry/pfam/PF00019\n\nPara extraer la información desde R, tenemos que familiarizarnos con la\nestructura de los datos.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npfam00019 <- fromJSON(paste0(API, 'protein/reviewed/entry/pfam/PF00019'))\nnames(pfam00019)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"count\"    \"next\"     \"previous\" \"results\" \n```\n\n\n:::\n\n```{.r .cell-code}\npfam00019[['count']]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 229\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(pfam00019[['results']])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"metadata\" \"entries\" \n```\n\n\n:::\n\n```{.r .cell-code}\n# La función \"flaten()\" corrige el anidamiento de marcos de datos,\nkable(flatten(pfam00019[['results']][['metadata']]))\n```\n\n::: {.cell-output-display}\n\n\n|accession |name                              |source_database | length|gene     |in_alphafold |in_bfvd |source_organism.taxId |source_organism.scientificName |source_organism.fullName                          |\n|:---------|:---------------------------------|:---------------|------:|:--------|:------------|:-------|:---------------------|:------------------------------|:-------------------------------------------------|\n|A1C2U3    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9600                  |Pongo pygmaeus                 |Pongo pygmaeus (Bornean orangutan)                |\n|A1C2U6    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9544                  |Macaca mulatta                 |Macaca mulatta (Rhesus macaque)                   |\n|A1C2U7    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9597                  |Pan paniscus                   |Pan paniscus (Pygmy chimpanzee)                   |\n|A1C2V0    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9598                  |Pan troglodytes                |Pan troglodytes (Chimpanzee)                      |\n|A1C2V5    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9595                  |Gorilla gorilla gorilla        |Gorilla gorilla gorilla (Western lowland gorilla) |\n|A8E7N9    |Growth/differentiation factor 6-B |reviewed        |    412|gdf6b    |TRUE         |FALSE   |7955                  |Danio rerio                    |Danio rerio (Zebrafish)                           |\n|A9CB18    |Growth/differentiation factor 9   |reviewed        |    455|GDF9     |TRUE         |FALSE   |9555                  |Papio anubis                   |Papio anubis (Olive baboon)                       |\n|F1QWZ4    |Growth/differentiation factor 2   |reviewed        |    389|gdf2     |TRUE         |FALSE   |7955                  |Danio rerio                    |Danio rerio (Zebrafish)                           |\n|G5EBY8    |BMP-like protein unc-129          |reviewed        |    407|unc-129  |TRUE         |FALSE   |6239                  |Caenorhabditis elegans         |Caenorhabditis elegans                            |\n|G5EEL5    |Protein dbl-1                     |reviewed        |    365|dbl-1    |TRUE         |FALSE   |6239                  |Caenorhabditis elegans         |Caenorhabditis elegans                            |\n|G7PWZ3    |Growth/differentiation factor 15  |reviewed        |    308|GDF15    |TRUE         |FALSE   |9541                  |Macaca fascicularis            |Macaca fascicularis (Crab-eating macaque)         |\n|O00292    |Left-right determination factor 2 |reviewed        |    366|LEFTY2   |TRUE         |FALSE   |9606                  |Homo sapiens                   |Homo sapiens (Human)                              |\n|O08689    |Growth/differentiation factor 8   |reviewed        |    376|Mstn     |TRUE         |FALSE   |10090                 |Mus musculus                   |Mus musculus (Mouse)                              |\n|O08717    |Inhibin beta E chain              |reviewed        |    350|Inhbe    |TRUE         |FALSE   |10090                 |Mus musculus                   |Mus musculus (Mouse)                              |\n|O13048    |Nodal homolog 4-A                 |reviewed        |    402|nodal4-a |TRUE         |FALSE   |8355                  |Xenopus laevis                 |Xenopus laevis (African clawed frog)              |\n|O14793    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9606                  |Homo sapiens                   |Homo sapiens (Human)                              |\n|O18828    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9557                  |Papio hamadryas                |Papio hamadryas (Hamadryas baboon)                |\n|O18830    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9940                  |Ovis aries                     |Ovis aries (Sheep)                                |\n|O18831    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9823                  |Sus scrofa                     |Sus scrofa (Pig)                                  |\n|O18836    |Growth/differentiation factor 8   |reviewed        |    375|MSTN     |TRUE         |FALSE   |9913                  |Bos taurus                     |Bos taurus (Bovine)                               |\n\n\n:::\n:::\n\n\n\n\n### Ejercicio 5\n\n*Intenta obtener una lista de los dominios de Pfam presentes en\nvertebrados (taxon 7742). Al menos, los 20 primeros.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvertebrados <- fromJSON(paste0(API, 'entry/pfam/taxonomy/uniprot/7742'))\nnames(vertebrados)\nvertebrados[['results']][['metadata']]\nkable(vertebrados)\n```\n:::\n\n\n\n\n> Se ha usado `#| eval: false` ,`#| message: false`y `#| warning: false`\n> para facilitar la visualización al renderizarlo.\n\n### Ejercicio 6\n\n*¿Cuántas proteínas de cocodrilos (taxon 8493) conocemos con el dominio\nzinc finger, C2HC type (Pfam PF01530)?*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npfam01530 <- fromJSON(paste0(API, 'protein/uniprot/entry/pfam/PF01530/taxonomy/uniprot/8493'))\nnames(pfam01530)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"count\"    \"next\"     \"previous\" \"results\" \n```\n\n\n:::\n\n```{.r .cell-code}\npfam01530[['count']]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15\n```\n\n\n:::\n:::\n\n\n\n\nSe conocen 15 proteínas de cocodrilos con el dominio *zinc finger, C2HC\ntype* (Pfam PF01530).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}