{
  "hash": "d15e7f5d5c23e5dbf1b50bd920d0d3ac",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análisis de expresión diferencial\"\nlang: es\ndate: today\nexecute: \n  output: true\n  error: true\nengine: knitr\nbibliography: ../../doc/references.bib\nlanguage:\n   title-block-published: \"Última actualización:\"\n   section-title-references: \"Bibliografía\"\nformat:\n   html:\n      embed-resources: true\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n# PRÁCTICA 12\n\n*¡OJO!* Es importante actualizar y descargar el paquete DESeq2, ya que\nlo utilizaremos en esta práctica.\n\n## Datos\n\nUtilizaremos las medidas de expresión génica del archivo\nsalmon.merged.gene_counts.ts (descargado desde el aula virtual). Los\ndatos proceden de 12 genotecas de RNA-seq de lecturas emparejadas, de\nmuestras de Drosophila melanogaster de dos orígenes geográficos (Panamá\ny Maine) y dos tratamientos de temperatura (low y high) (Zhao 2015). Hay\n3 réplicas biológicas para cada combinación de región y temperatura.\nAdemás, necesitáis el archivo dme_elev_samples.tsv, una tabla que indica\na qué región y tratamiento pertenece cada muestra (descargado desde el\naula virtual). Los dos archivos deben estar guardados en la carpeta de\ndatos.\n\n## Exploración de los datos\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmuestras <- read.table('../../data/dme_elev_samples.tsv', header = TRUE)\ngenex <- read.table('../../data/salmon.merged.gene_counts.tsv',\n                    header = TRUE)\nmuestras\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       sample population temp\n1  SRR1576457      maine  low\n2  SRR1576458      maine  low\n3  SRR1576459      maine  low\n4  SRR1576460      maine high\n5  SRR1576461      maine high\n6  SRR1576462      maine high\n7  SRR1576463     panama  low\n8  SRR1576464     panama  low\n9  SRR1576465     panama  low\n10 SRR1576514     panama high\n11 SRR1576515     panama high\n12 SRR1576516     panama high\n```\n\n\n:::\n:::\n\n\n\n\n### Ejercicio 1\n\n*Recuerda dejar constancia en un bloque de código de cómo obtienes las\nrespuestas.*\n\n*A) Usa la función paste() para añadir una columna a muestras que\ncontenga la población y la temperatura unidas por \\_.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmuestras$nueva_columna <- paste(muestras$population, muestras$temp, sep = \"_\")\nmuestras$nueva_columna\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"maine_low\"   \"maine_low\"   \"maine_low\"   \"maine_high\"  \"maine_high\" \n [6] \"maine_high\"  \"panama_low\"  \"panama_low\"  \"panama_low\"  \"panama_high\"\n[11] \"panama_high\" \"panama_high\"\n```\n\n\n:::\n:::\n\n\n\n\n*B) ¿Cuál es el número total de lecturas por muestra?*\n\nEl dataframe genex tiene el dataframe del gen y una columna por cada\nmuestra, los números que vemos son \"counts\". Es un recuento del número\nde lecturas que mapean en cada uno de los genes/muestras proveniendo del\nRNASeq. Si pone un punto en el número es porque el programa no está\n\"seguro\" acerca del recuento y pone un decimal. No lo tenemos que\naplicar a toda la sumas de columnas, ya que las dos primeras no son\nnúmeros, entonces no deben ser sumadas. Vemos que hay entre 20-30\nmillones de lecturas por muestra. Si hay 20.000 genes y entre 20-30\nmillones de lecturas por muestra nos hacemos la idea de lecturas por\ngen.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_lecturas <- colSums(genex[ , -c (1,2)])\ntotal_lecturas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSRR1576457 SRR1576458 SRR1576459 SRR1576460 SRR1576461 SRR1576462 SRR1576463 \n  28252778   21565448   29471559   27692134   26953900   29368135   29706071 \nSRR1576464 SRR1576465 SRR1576514 SRR1576515 SRR1576516 \n  26757043   26596118   30950499   25563787   24401671 \n```\n\n\n:::\n:::\n\n\n\n\n*C) ¿Los recuentos tienen distribuciones parecidas entre muestras?*\n\nPara separar las muestras metemos las columnas una bajo de otra, para\nello usamos pivot_longer. Enviamos los nombres a la variable muestra y\nlos valores a la de expresion. Aparecen algunos errores porque son\nvalores (de expresión) con cero, es decir, no se expresan los genes (y\nnosotros estamos usando logaritmos). A continuación vemos un violin\nplot.\n\n**Nota:** he añadido en el siguiente código *warning:false* y\n*message:false*, ya que salía un error a la hora de representar.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(ggplot2)\ngenex_long <- pivot_longer(genex, 3:14, names_to = 'muestra', values_to = 'expression')\nggplot(data = genex_long, mapping = aes(x = muestra, y = expression)) + geom_violin() + scale_y_continuous(trans = 'log')\n```\n\n::: {.cell-output-display}\n![](P12_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\nOtra opción sería la función pairs acepta una matriz/dataframe de datos\nnuméricos.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(genex[, -c(1,2)])\n```\n\n::: {.cell-output-display}\n![](P12_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\nLa función pairs muestra la nube de puntos de cada pareja. La mayor\nparte de muestras tienen una expresión baja, se concentran todos en la\nesquina inferior izquierda. Tenemos muchos paneles, podríamos haberlo\nhecho condición por condición.\n\n*D) ¿Cuántos genes no se expresan en absoluto en ninguna de las\nmuestras?*\n\nIgualamos a cero para crear un vector de verdadero y falso, así nos\ndicen en cuántos genes la expresión es cero. En este caso, hay 4722\ngenes sin expresión.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenes_sin_expresion <- sum(rowSums(genex[, -c(1,2)]) ==0)\ngenes_sin_expresion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4722\n```\n\n\n:::\n:::\n\n\n\n\n## Crear el objeto de clase DESeqDataSet\n\nPara crear un objeto de clase DESeqDataSet necesitamos que las filas de\nla tabla muestras estén en el mismo orden que las columnas en genex. La\nfunción DESeqDataSetFromMatrix() necesita que los recuentos sean una\nmatriz, no un marco de datos. Y en muestras debe haber factores.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages(library('DESeq2'))\nall(names(genex)[3:14] == muestras$sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pasamos la columna \"sample\" a nombres de fila:\nrow.names(muestras) <- muestras$sample\n# Eliminamos la columna \"sample\":\nmuestras$sample <- NULL\n# Y convertimos \"population\" y \"temp\" en factores:\nmuestras$population <- factor(muestras$population,\n                              levels = c('maine', 'panama'))\nmuestras$temp       <- factor(muestras$temp,\n                              levels = c('low', 'high'))\nmuestras\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           population temp nueva_columna\nSRR1576457      maine  low     maine_low\nSRR1576458      maine  low     maine_low\nSRR1576459      maine  low     maine_low\nSRR1576460      maine high    maine_high\nSRR1576461      maine high    maine_high\nSRR1576462      maine high    maine_high\nSRR1576463     panama  low    panama_low\nSRR1576464     panama  low    panama_low\nSRR1576465     panama  low    panama_low\nSRR1576514     panama high   panama_high\nSRR1576515     panama high   panama_high\nSRR1576516     panama high   panama_high\n```\n\n\n:::\n:::\n\n\n\n\nAunque no hacía falta definir los niveles de los factores, este es un\nbuen momento para definir manualmente su orden (por defecto se ordenan\nalfabéticamente). El orden de los niveles determina qué nivel actúa como\nreferencia en los contrastes estadísticos (el primero). Esto resultaría\nimportante, por ejemplo, al comparar tratamientos respecto de un\ncontrol.\n\nLos datos de recuento deben ser números enteros y en forma de matriz.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrow.names(genex) <- genex$gene_name\ngenex$gene_name <- NULL\ngenex$gene_id   <- NULL\ngenex <- round(as.matrix(genex))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndds1 <- DESeqDataSetFromMatrix(\n   countData = genex,\n   colData = muestras,\n   design = ~ population + temp\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nconverting counts to integer mode\n```\n\n\n:::\n\n```{.r .cell-code}\ndds1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: DESeqDataSet \ndim: 24254 12 \nmetadata(1): version\nassays(1): counts\nrownames(24254): 7SLRNA:CR32864 a ... RR51477 Bari1{}RR51478\nrowData names(0):\ncolnames(12): SRR1576457 SRR1576458 ... SRR1576515 SRR1576516\ncolData names(3): population temp nueva_columna\n```\n\n\n:::\n:::\n\n\n\n\n**Nota:** los objetos DESeqDataSet pueden contener información sobre las\ncoordenadas cromosómicas de los genes o tránscritos, si se construyen a\npartir de otro tipo de datos.\n\n## Pre-filtrado\n\nUna fracción importante de genes no se están expresando en ningúna\nmuestra. Aunque el filtrado no es necesario, ayuda a reducir la memoria\nocupada por dds1:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkeep <- rowSums(counts(dds1)) > 0\ndds1 <- dds1[keep, ]\n```\n:::\n\n\n\n\n## Expresión diferencial\n\nObserva que la función DESeq() produce un objeto también de clase\nDESeqDataSet, pero con resultados añadidos:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds1 <- DESeq(dds1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nestimating size factors\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nestimating dispersions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\ngene-wise dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nmean-dispersion relationship\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nfinal dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nfitting model and testing\n```\n\n\n:::\n:::\n\n\n\n\nVemos que nos produce los resultados entre el contraste del último nivel\ny del factor en la tabla.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- results(dds1)\nres\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2 fold change (MLE): temp high vs low \nWald test p-value: temp high vs low \nDataFrame with 19508 rows and 6 columns\n                baseMean log2FoldChange     lfcSE       stat      pvalue\n               <numeric>      <numeric> <numeric>  <numeric>   <numeric>\n7SLRNA:CR32864   346.333      0.5918974 1.3301901   0.444972 0.656339979\na                555.596     -0.2730041 0.0718487  -3.799710 0.000144866\nabd-A            531.996     -0.0286785 0.0789218  -0.363379 0.716321732\nAbd-B            634.760     -0.1083918 0.0771241  -1.405421 0.159896272\nAbl             1654.842     -0.1328055 0.0746580  -1.778851 0.075264257\n...                  ...            ...       ...        ...         ...\nRR51007          4.90906      3.8596869  2.972471  1.2984773 1.94123e-01\nRR51048         16.60710     -0.8973071  0.341603 -2.6267541 8.62036e-03\nRR51093         36.93279      0.0660523  1.685323  0.0391927 9.68737e-01\nRR51475        159.62678     -2.6058194  1.875172 -1.3896429 1.64637e-01\nRR51477         70.83394      1.6927986  0.192437  8.7966393 1.40975e-18\n                      padj\n                 <numeric>\n7SLRNA:CR32864  0.81170166\na               0.00154573\nabd-A           0.85146289\nAbd-B           0.33849217\nAbl             0.20046220\n...                    ...\nRR51007        3.82417e-01\nRR51048        4.01745e-02\nRR51093        9.84464e-01\nRR51475        3.44815e-01\nRR51477        2.06427e-16\n```\n\n\n:::\n:::\n\n\n\n\nPor defecto, la función results() produce la tabla de resultados para el\ncontraste entre el nivel último y el de referencia del último factor en\nla tabla que describe las muestras. En este caso, el factor es temp, el\nnivel de referencia es low y el otro nivel es high. Por tanto, los\nvalores de log2FoldChange representan el logaritmo en base 2 de la\nrelación entre niveles de expresión en muestras high respecto de\nmuestras low.\n\nEn referencia a estos resultados: log2foldchange - logaritmo en base 2\nde la relación de cambio. Valores positivos son genes que a temperatura\nalta se expresan más que en baja. El nivel de expresión es mayor a\ntemperatura baja para los valores negativos. Tenemos un dataframe con\n19.508 filas (esto es porque hemos prefiltrado y hemos eliminado los que\ntienen una expresión muy baja).\n\n### Ejercicio 3\n\n*A) Mira la ayuda de results() y genera también la tabla de resultados\npara el contraste entre las dos regiones de procedencia de las moscas.*\n\nRepetimos lo que hemos realizado anteriormente:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds1_2 <- DESeqDataSetFromMatrix(\n   countData = genex,\n   colData = muestras,\n   design = ~ population\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nconverting counts to integer mode\n```\n\n\n:::\n\n```{.r .cell-code}\ndds1_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: DESeqDataSet \ndim: 24254 12 \nmetadata(1): version\nassays(1): counts\nrownames(24254): 7SLRNA:CR32864 a ... RR51477 Bari1{}RR51478\nrowData names(0):\ncolnames(12): SRR1576457 SRR1576458 ... SRR1576515 SRR1576516\ncolData names(3): population temp nueva_columna\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkeep <- rowSums(counts(dds1_2)) > 0\ndds1_2 <- dds1_2[keep, ]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndds1_2 <- DESeq(dds1_2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nestimating size factors\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nestimating dispersions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\ngene-wise dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nmean-dispersion relationship\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nfinal dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nfitting model and testing\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nres2 <- results(dds1_2)\nres2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2 fold change (MLE): population panama vs maine \nWald test p-value: population panama vs maine \nDataFrame with 19508 rows and 6 columns\n                baseMean log2FoldChange     lfcSE       stat     pvalue\n               <numeric>      <numeric> <numeric>  <numeric>  <numeric>\n7SLRNA:CR32864   346.333     -0.3405225 1.2828671  -0.265439  0.7906716\na                555.596     -0.1061901 0.1079132  -0.984033  0.3250994\nabd-A            531.996      0.0468148 0.0780163   0.600065  0.5484628\nAbd-B            634.760     -0.0386942 0.0827328  -0.467701  0.6399985\nAbl             1654.842     -0.1435019 0.0846880  -1.694478  0.0901746\n...                  ...            ...       ...        ...        ...\nRR51007          4.90906      1.0441599  2.913048  0.3584424 0.72001228\nRR51048         16.60710     -1.2841124  0.397258 -3.2324379 0.00122739\nRR51093         36.93279     -0.8907347  1.591194 -0.5597901 0.57562259\nRR51475        159.62678     -0.0858284  1.937892 -0.0442896 0.96467360\nRR51477         70.83394     -0.2603940  0.461897 -0.5637486 0.57292520\n                    padj\n               <numeric>\n7SLRNA:CR32864  0.966622\na               0.790762\nabd-A           0.907772\nAbd-B           0.928931\nAbl             0.523390\n...                  ...\nRR51007        0.9498358\nRR51048        0.0472064\nRR51093        0.9181683\nRR51475        0.9967946\nRR51477        0.9169334\n```\n\n\n:::\n:::\n\n\n\n\nTambién lo podemos hacer así (no lo pongo en código de bloque de R para\nevitar sobreescribir los datos de antes): res2 \\<- results(dds1,\ncontrast = c('population', 'panama', 'maine'))\n\nOtro: p-valor ajustado para resolver el problema de los tests múltiples.\n\n*B) Usa summary() sobre los resultados para ver el número de genes\ndiferencialmente expresados entre cada par de condiciones.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nout of 19508 with nonzero total read count\nadjusted p-value < 0.1\nLFC > 0 (up)       : 2418, 12%\nLFC < 0 (down)     : 2336, 12%\noutliers [1]       : 90, 0.46%\nlow counts [2]     : 3018, 15%\n(mean count < 2)\n[1] see 'cooksCutoff' argument of ?results\n[2] see 'independentFiltering' argument of ?results\n```\n\n\n:::\n:::\n\n\n\n\nTenemos un 12% de genes up-regulated o sobreexpresados ene temperaturas\naltas sobre bajas, también un 12% de subexpresados. Outliers tenemos 90\ny low counts 3018.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(res2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nout of 19508 with nonzero total read count\nadjusted p-value < 0.1\nLFC > 0 (up)       : 350, 1.8%\nLFC < 0 (down)     : 351, 1.8%\noutliers [1]       : 46, 0.24%\nlow counts [2]     : 2270, 12%\n(mean count < 1)\n[1] see 'cooksCutoff' argument of ?results\n[2] see 'independentFiltering' argument of ?results\n```\n\n\n:::\n:::\n\n\n\n\nTenemos porcentaje bastante equilibrado entre main y panama. La\ntemperatura causa la sobreexpresión. Nota: En clase hemos probado este\nbloque de código pero me da distinto. Debería dar LFC \\> 0 de 623 y LFC\n\\< 0 de 634. Los outliers deberían ser de 90 y low count de 3018.\n\n*C) ¿Cuál es la tasa de falsos positivos (FDR)?*\n\nEn summary podemos apreciar que el FDR es menor de 0,1 en ambos casos.\nEsto podemos conocerlo de la siguiente forma: en la función results\ntenemos un parametro alfa que es por defecto 0,1. Por su definición alfa\nes el umbral de significancia utilziado para filtrar el filtrado\nindependiente. Si somos más exigentes y no lo toleramos y lo queremos\nhacer con 0,5 lo cambiamos. Este no ha sido el caso de esta práctica.\n\n## Gráficas\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotMA(res)\n```\n\n::: {.cell-output-display}\n![](P12_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\nEste plot es simétrico y centrado en cero. Vemos el logFC según el nivel\nde expresión. Vemos que hay una dispersión grande.\n\nLos genes con niveles de expresión más bajos producen resultados más\nruidosos (la varianza es mayor). La función lfcShrink() contrae (shrink)\nlas estimaciones de los efectos (log fold change) para reducir el ruido\ny hacer el resultado más realista: Aplicamos empirical bayes que es una\nforma de descomprimir. Lo comprime asumiendo que el logFC lo calcula con\nerror. Vemos que ha disminuido la escala del logFC. Es una forma de ser\nmás conservadores, estimamos la variación pero con muy pocas réplicas.\nSi asumimos que la tasas de cambio está entre 0,5 y -0,5, vemos que hay\ndispersión pero la media está muy concentrada. Suponemos que los valores\nelevados o bajos con pocas muestra se parecen más a la muestra, lo que\nhace es comprimirlo.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresShrink <- lfcShrink(dds1, coef = 'temp_high_vs_low',\n                       type = 'normal')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nusing 'normal' for LFC shrinkage, the Normal prior from Love et al (2014).\n\nNote that type='apeglm' and type='ashr' have shown to have less bias than type='normal'.\nSee ?lfcShrink for more details on shrinkage type, and the DESeq2 vignette.\nReference: https://doi.org/10.1093/bioinformatics/bty895\n```\n\n\n:::\n\n```{.r .cell-code}\nplotMA(resShrink)\n```\n\n::: {.cell-output-display}\n![](P12_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n\n### Ejercicio 4\n\n*¿Sabrías hacer una gráfica volcán?*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_df <- as.data.frame(res)\n\nvolcano <- ggplot(res_df, aes(x = log2FoldChange, y = -log10(padj))) +\n  geom_point(alpha = 0.5) +\n  labs(title = \"Volcano Plot\", x = \"resShrink\", y = \"-log10(P-value)\") +\n  theme_minimal()\n\nprint(volcano)\n```\n\n::: {.cell-output-display}\n![](P12_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n\n## Extraer datos transformados\n\nAunque los datos de entrada no deben estar normalizados y la función\nDESeq() ya tiene en cuenta las diferencias de tamaño de genoteca entre\nmuestras y la relación entre media y varianza, puede ser útil disponer\nde los datos normalizados para representarlos gráficamente. Para ello\npodemos usar las funciones vst() y assay():\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds2 <- vst(dds1)\nNormCounts <- assay(dds2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- res[! is.na(res$pvalue), ]\nres <- res[order(res$log2FoldChange),]\nheatmap(NormCounts[c(head(row.names(res), 100),\n                     tail(row.names(res), 100)), ],\n        Rowv = NA, Colv = NA)\n```\n\n::: {.cell-output-display}\n![](P12_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\n### Ejercicio 5\n\n*¿Podrías explicar qué hace el bloque de código anterior?*\n\n-   vst tiene la función de estimar la tendencia de la dispersió\n    (Quickly estimate dispersion trend and apply a variance stabilizing\n    transformation).\n\n-   assay contiene una matriz donde las filas representan objetos de\n    interés y las columnas representan las muestras.\n\n**Nota:** He consultado help(vst) y help(assay) respectivamente.\n\n### Ejercicio 6\n\n*A) En [este\nenlace](https://aulavirtual.uv.es/pluginfile.php/6039768/mod_resource/content/1/guio-es.html)\nanalizan exactamente los mismos datos con otro paquete de R: `limma`.\nUna de sus conclusiones es se sobreexpresan más genes en temperatura\nbaja que en temperatura alta. ¿Confirma tu análisis esta conclusión?*\n\nRecapitulando con la primera parte de la práctica, yo he visualizado\nestos valores mediante summary(res). De esta forma, llegué a la\nconclusión de se están expresando más genes a temperatura alta: 2418 se\nsobreexpresan en temperatura alta 2336 se sobreexpresan en temperatura\nbaja No obstante, el enlace no me redirige, así que no puedo comparar\nlos resultados. Mi análisis se confirmaría en el caso de que en el otro\nanálisis también se llegue a la conclusión de que hay más genes\nsobreexpresados en temperatura alta.\n\n*B) Estos son los 10 genes más diferencialmente expresados según aquel\nanálisis entre las condiciones de baja y alta temperatura:*\n\n|   | logFC | AveExpr | t | P.Value | adj.P.Val | B |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| **Cpr92F** | 2.473527 | 6.201774 | 24.28881 | 1.306910e-13 | 1.739105e-09 | 21.29258 |\n| **Vajk3** | 1.675184 | 4.029281 | 21.90298 | 6.069753e-13 | 3.524528e-09 | 19.66813 |\n| **lncRNA:CR46017** | -3.974938 | 1.044005 | -21.50807 | 7.945880e-13 | 3.524528e-09 | 16.80878 |\n| **CG7214** | 2.198970 | 7.945664 | 20.75054 | 1.349821e-12 | 4.490516e-09 | 19.14847 |\n| **CG3739** | -2.869172 | 6.514652 | -20.49734 | 4.414988e-12 | 1.175005e-08 | 18.01975 |\n| **Acp1** | 2.231834 | 7.638125 | 17.79441 | 2.089853e-11 | 3.997808e-08 | 16.54909 |\n\n: He elaborado la tabla a partir de los resultados que se ven en el\nguion del Aula Virtual\n\n*¿Cómo se comparan estos resultados con los tuyos?*\n\nMediante el siguiente código voy a comprobar mis valores para estos\ngenes:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres[c(\"Cpr92F\", \"Vajk3\", \"Acp1\",\"CG3739\", \"CG7214\"), ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2 fold change (MLE): temp high vs low \nWald test p-value: temp high vs low \nDataFrame with 5 rows and 6 columns\n        baseMean log2FoldChange     lfcSE      stat      pvalue        padj\n       <numeric>      <numeric> <numeric> <numeric>   <numeric>   <numeric>\nCpr92F  2718.979       -2.39126 0.1172256  -20.3988 1.71374e-92 1.40527e-88\nVajk3    513.411       -1.65423 0.0886464  -18.6610 1.02701e-77 3.36859e-74\nAcp1    7042.192       -2.17394 0.1217046  -17.8624 2.31289e-71 4.21460e-68\nCG3739  3912.044        2.93354 0.1497441   19.5903 1.86963e-85 7.66550e-82\nCG7214  8615.934       -2.14594 0.1178994  -18.2015 5.02408e-74 1.17707e-70\n```\n\n\n:::\n:::\n\n\n\n\nA través de esto, y retomando el apartado A, veo que los resultados\nestán \"invertidos\". Esto lo observo mediante el FC, ya que cuando me da\npositivo a mi, en el análisis por limma da negativo. Esto quiere decir\nque yo para calcular el FC lo he hecho temp alta/temp bajo, mientras que\nen el analisis por limma se ha hecho temp baja/temp alta. Para poder\ncomprobar los resultados probaríamos a calcular el FC de la misma forma\nque en el otro estudio.\n",
    "supporting": [
      "P12_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}