{
  "hash": "dd0b14f0b6ec80d6d7e7388b59a961af",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Reconstrucción filogenética\"\nlang: es\ndate: today\nexecute: \n  output: true\n  error: true\nengine: knitr\nbibliography: ../../doc/references.bib\nlanguage:\n   title-block-published: \"Última actualización:\"\n   section-title-references: \"Bibliografía\"\nformat:\n   html:\n      embed-resources: true\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n# PRÁCTICA 9\n\n## Introducción\n\nAunque existen muy buenos programas para inferir filogenias fuera del\nentorno de R (es decir, para el terminal de Bash), utilizar las\nherramientas en R tiene la ventaja de poder representar los árboles,\nmanipularlos y extraer información de ellos con toda la flexibilidad que\npermite un lenguaje de programación. Otros programas como RAxML o IQtree\nproducirían los resultados en forma de archivos de texto con formato\nNewick o NEXUS. En R, los árboles serán objetos de clase phylo, que\npueden también ser exportados como archivos de texto con formato Newick\ncon la función write.tree() del paquete ape. Este paquete será cargado\nautomáticamente cuando carguemos el paquete phangorn, que proporciona\nlas principales funciones para inferencia filogenética.\n\n## Objetivos\n\n1.  Se busca obtener una filogenia calibrada de hominidos y primates a\n    partir de secuencias mitocondriales.\n\n## Datos\n\nDescargamos un alineamiento en formato FASTA de 42 cromosomas\nmitocondriales completos de: 1 Gorila, 1 Homo heidelbergensis (de hace\n400.000 años), 4 humanos denisovanos (de hace entre 30.000 y 110.000\naños), 19 humanos neandertales (de hace entre 30.000 y 180.000 años), 9\nhumanos anatómicamente modernos (actuales).\n\nEl archivo descargado recibe el nombre de mtDNA.fasta y se ha guardado\nen la carpeta \"data\".\n\nA continuación ejecutamos el siguiente bloque para cargar el paquete\nphangorn (que previamente hemos instalado):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(phangorn)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: ape\n```\n\n\n:::\n\n```{.r .cell-code}\nmtdna <- read.phyDat('../../data/mtDNA.fasta', format = 'fasta')\n```\n:::\n\n\n\n\nTras ejecutar el bloque anterior, se cargan los datos en el objeto de\nclase phyDat llamado mtdna. Con la función glance() observamos los datos\no con image() podemos generar una imagen del alineamiento.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(mtdna)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  nseq nchar unique_site_pattern parsimony_informative_sites const_sites\n1   42 16603                 974                        2047       13482\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nimage(mtdna)\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n### Ejercicio 1\n\n*¿Puedes confirmar el número de secuencias? ¿Qué longitud tiene el\nalineamiento? ¿Qué función usarías para extraer los nombres de las\nsecuencias?*\n\nCon la función glance() que ha sido usada anteriormente, descubrimos que\nhay 42 secuencias (nseq) y que la longitud del alineamiento es de 16603\ncaracters (nchar). Para extraer los nombres de las secuencias utilizamos\nla función names().\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(mtdna)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"G.gorilla_D38114\"            \"P.troglodytes_JF727212\"     \n [3] \"P.troglodytes_JN191207\"      \"P.troglodytes_JF727168\"     \n [5] \"P.troglodytes_HM068590\"      \"P.paniscus_KX211934\"        \n [7] \"P.paniscus_KX211928\"         \"P.paniscus_GU189658\"        \n [9] \"P.paniscus_GU189664\"         \"H.heidelbergensis_NC_023100\"\n[11] \"H.s.denisova_NC_013993\"      \"H.s.denisova_FR695060\"      \n[13] \"H.s.denisova_KX663333\"       \"H.s.denisova_KT780370\"      \n[15] \"H.s.neandertal_KX198085\"     \"H.s.neandertal_KX198086\"    \n[17] \"H.s.neandertal_MG025538\"     \"H.s.neandertal_NC_011137\"   \n[19] \"H.s.neandertal_FM865409\"     \"H.s.neandertal_FM865407\"    \n[21] \"H.s.neandertal_KX198088\"     \"H.s.neandertal_KX198083\"    \n[23] \"H.s.neandertal_MG025540\"     \"H.s.neandertal_MG025536\"    \n[25] \"H.s.neandertal_MG025537\"     \"H.s.neandertal_KX198087\"    \n[27] \"H.s.neandertal_KX198082\"     \"H.s.neandertal_FM865408\"    \n[29] \"H.s.neandertal_KU131206\"     \"H.s.neandertal_KF982693\"    \n[31] \"H.s.neandertal_FM865411\"     \"H.s.neandertal_KY751400\"    \n[33] \"H.s.neandertal_MK033602\"     \"H.s.modern_EU092846\"        \n[35] \"H.s.modern_EU092665\"         \"H.s.modern_JQ045086\"        \n[37] \"H.s.modern_DQ779927\"         \"H.s.modern_DQ779932\"        \n[39] \"H.s.modern_AP008640\"         \"H.s.modern_AY495317\"        \n[41] \"H.s.modern_J01415\"           \"H.s.modern_FJ236981\"        \n```\n\n\n:::\n:::\n\n\n\n\n## Árboles basados en distancias\n\nLos árboles NJ y UPGMA pueden proporcionar una idea rápida de cómo\npodría ser la relación filogenética entre las secuencias. Como métodos\nbasados en distancias que son, necesitamos calcular primero las\ndistancias. Podemos hacerlo en el mismo paso en el que generamos el\nárbol: nj(dist.ml(mtdna)). O bien, podemos hacerlo en dos pasos: guardar\nla matriz de distancias en un objeto de clase dist, y después generar\nlos árboles.\n\nLa función dist.ml() (de phangorn) solo ofrece un par de modelos de\nevolución de nucleótidos para estimar distancias: F81 y JC69 (ofrece 17\nmodelos para proteínas). La función dist.dna() de ape (que no se aplica\nsobre objetos phyDat, sino DNAbin) ofrece algunas opciones más. Pero en\nel fondo, los métodos NJ y UPGMA son sólo heurísticos rápidos, con los\nque no hace falta usar distancias de alta precisión.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistancias <- dist.ml(mtdna, model = 'F81')\nmt_nj    <- NJ(distancias)\nmt_upgma <- upgma(distancias)\n```\n:::\n\n\n\n\n## Ejercicio 2\n\n*A) ¿De qué clase son los objetos mt_nj y mt_upgma?*\n\nPara conocer la clase de los objetos utilizo class(). En este caso se\nobserva que ambos son de clase \"phylo\", es decir, son objetos en los que\nse guarda la información sobre la estructura del árbol filogénetico.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(mt_nj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"phylo\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(mt_upgma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"phylo\"\n```\n\n\n:::\n:::\n\n\n\n\n*B) Consulta la estructura de estos objetos.*\n\nPara observar la estructura de ambos objetos utilizo str(). Esta función\nnos proporciona información sobre la estructura interna de un objeto de\nR.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(str(mt_nj))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 4\n $ edge       : int [1:81, 1:2] 47 47 54 54 53 53 52 52 51 51 ...\n $ edge.length: num [1:81] 6.03e-05 5.20e-08 -4.37e-08 4.37e-08 8.51e-08 ...\n $ tip.label  : chr [1:42] \"G.gorilla_D38114\" \"P.troglodytes_JF727212\" \"P.troglodytes_JN191207\" \"P.troglodytes_JF727168\" ...\n $ Nnode      : int 40\n - attr(*, \"class\")= chr \"phylo\"\n - attr(*, \"order\")= chr \"postorder\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n(str(mt_upgma))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 4\n $ edge       : int [1:82, 1:2] 63 63 49 49 48 48 59 59 55 55 ...\n $ edge.length: num [1:82] 0.00127 0.00127 0.001422 0.000151 0.011063 ...\n $ tip.label  : chr [1:42] \"G.gorilla_D38114\" \"P.troglodytes_JF727212\" \"P.troglodytes_JN191207\" \"P.troglodytes_JF727168\" ...\n $ Nnode      : int 41\n - attr(*, \"class\")= chr \"phylo\"\n - attr(*, \"order\")= chr \"postorder\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n:::\n\n\n\n\n*C) Represéntalos gráficamente (plot(mt_nj)) y consulta la ayuda de la\nfunción plot.phylo() para saber qué opciones de representación gráfica\ntienes.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(plot(mt_nj))\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$type\n[1] \"phylogram\"\n\n$use.edge.length\n[1] TRUE\n\n$node.pos\n[1] 1\n\n$node.depth\n[1] 1\n\n$show.tip.label\n[1] TRUE\n\n$show.node.label\n[1] FALSE\n\n$font\n[1] 3\n\n$cex\n[1] 1\n\n$adj\n[1] 0\n\n$srt\n[1] 0\n\n$no.margin\n[1] FALSE\n\n$label.offset\n[1] 0\n\n$x.lim\n[1] 0.0000000 0.1535281\n\n$y.lim\n[1]  1 42\n\n$direction\n[1] \"rightwards\"\n\n$tip.color\n[1] \"black\"\n\n$Ntip\n[1] 42\n\n$Nnode\n[1] 40\n\n$root.time\nNULL\n\n$align.tip.label\n[1] FALSE\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.phylo(mt_nj)\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\n*D) Para qué sirven las funciones add.scale.bar() y axisPhylo()?*\n\nPara contestar esta pregunta he consultado help(add.scale.bar) y\nhelp(axisPhylo).\n\n-   **add.scale.bar:** Esta función añade una barra horizontal que\n    indica la escala de las longitudes de las ramas a la representación\n    gráfica de un árbol filogenético en el dispositivo gráfico actual.\n\n-   **axisPhylo:** Esta función añade un eje escalado al lado de un\n    gráfico filogenético.\n\n## Enraizar\n\n## Escogiendo el nodo\n\nEl árbol mt_nj no está enraizado, se comprueba de la siguiente manera:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.rooted(mt_nj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n\nAl ejecutarlo [nos dice \\[FALSE\\]]{.underline}, por lo que se confirma\nque no esta enraizado. Para enraizarlo podemos usar la función root()\npero primero hay que indicarr el outgroup o nodo interno en el que se\nquiere situar la raíz. No obstante, primero para saber identificar los\nnodos internos invocamos nodelabels() tras haber usado plot(mt_nj). P*or\nejemplo, el nodo 75 parece ser el ancestro entre gorilas y chimpancés, y\npor tanto también es ancestro de los humanos*.\n\nPor tanto:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_nj_rooted <- root(mt_nj, node = 75)\nmt_nj_rooted\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPhylogenetic tree with 42 tips and 40 internal nodes.\n\nTip labels:\n  G.gorilla_D38114, P.troglodytes_JF727212, P.troglodytes_JN191207, P.troglodytes_JF727168, P.troglodytes_HM068590, P.paniscus_KX211934, ...\n\nUnrooted; includes branch length(s).\n```\n\n\n:::\n:::\n\n\n\n\nEn este caso obtenemos también un árbol filogenético con 42 puntas y 40\npuntos internos.\n\n## Con un *outgroup*\n\nLa numeración de los nodos internos siempre sigue a la de las hojas (o\npuntas) del árbol. El orden es caprichoso y después de enraizar, lo que\nera el 75 en mt_nj ahora será el 43 en mt_nj_rooted. Para garantizar que\nel enraizado no depende de la numeración, es más seguro usar el nombre\ndel outgroup:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_nj_rooted <- root(mt_nj, outgroup = 'G.gorilla_D38114')\nmt_nj_rooted\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPhylogenetic tree with 42 tips and 40 internal nodes.\n\nTip labels:\n  G.gorilla_D38114, P.troglodytes_JF727212, P.troglodytes_JN191207, P.troglodytes_JF727168, P.troglodytes_HM068590, P.paniscus_KX211934, ...\n\nUnrooted; includes branch length(s).\n```\n\n\n:::\n:::\n\n\n\n\nEn este caso también da un árbol filogenético con 42 puntos y 40 nodos\ninternos.\n\n## En un punto medio\n\nAl representar el árbol enraizado (plot(mt_nj_rooted)) verás que no\ntodas las hojas del árbol están a la misma altura. El punto exacto en el\nque se sitúa la raíz en una rama es arbitrario y root() no se esfuerza\nmucho en intentar que el árbol parezca ultramétrico. La otra opción es\nla función midpoint(), que escoge la posición de la raíz para que el\nárbol esté más equilibrado:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Esto sobreescribe el objeto anterior:\n#|fig-width: 12\n#|fig-height: 12\nmt_nj_rooted <- midpoint(mt_nj)\nplot(mt_nj_rooted, align.tip.label = TRUE, main = 'NJ, enraizado en punto medio')\nnodelabels(frame = 'none')\nadd.scale.bar()\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n## Con datación de hojas\n\nEl enraizado en punto medio asume que todas las hojas son\ncontemporáneas, como sucede en muchos casos. Pero, en nuestros datos\ntenemos secuencias contemporáneas y también arcaicas. Conociendo estas\nedades, podemos aplicar un método de enraizado llamado root-to-tip\nregression, mediante la función rtt() de ape.\n\nLo primero es crear un vector de fechas (o edades) para todas las hojas\ndel árbol. Podemos expressar las edades de las secuencias arcaicas como\nel número (negativo) de años que hace que dejaron de evolucionar. Para\nsaber el orden en que debemos especificar las edades, podemos usar\nmt_nj\\$tip.label.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfechas <- c(0, 0, 0, 0, 0, 0, 0, 0, 0,\n            -400000,\n            -39000, -50000, -110000, -110000,\n            -39820, -40096, -38515, -38310, -39000, -40000, -41210,\n            -42430, -42540, -43230, -43780, -44290, -44770, -49000,\n            -50000, -82752, -65000, -122287, -110450,\n            0, 0, 0, 0, 0, 0, 0, 0, 0)\n# Observa que hay que asignar el resultado de setNames() a \"fechas\"\nfechas <- setNames(fechas, mt_nj$tip.label)\nfechas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           G.gorilla_D38114      P.troglodytes_JF727212 \n                          0                           0 \n     P.troglodytes_JN191207      P.troglodytes_JF727168 \n                          0                           0 \n     P.troglodytes_HM068590         P.paniscus_KX211934 \n                          0                           0 \n        P.paniscus_KX211928         P.paniscus_GU189658 \n                          0                           0 \n        P.paniscus_GU189664 H.heidelbergensis_NC_023100 \n                          0                     -400000 \n     H.s.denisova_NC_013993       H.s.denisova_FR695060 \n                     -39000                      -50000 \n      H.s.denisova_KX663333       H.s.denisova_KT780370 \n                    -110000                     -110000 \n    H.s.neandertal_KX198085     H.s.neandertal_KX198086 \n                     -39820                      -40096 \n    H.s.neandertal_MG025538    H.s.neandertal_NC_011137 \n                     -38515                      -38310 \n    H.s.neandertal_FM865409     H.s.neandertal_FM865407 \n                     -39000                      -40000 \n    H.s.neandertal_KX198088     H.s.neandertal_KX198083 \n                     -41210                      -42430 \n    H.s.neandertal_MG025540     H.s.neandertal_MG025536 \n                     -42540                      -43230 \n    H.s.neandertal_MG025537     H.s.neandertal_KX198087 \n                     -43780                      -44290 \n    H.s.neandertal_KX198082     H.s.neandertal_FM865408 \n                     -44770                      -49000 \n    H.s.neandertal_KU131206     H.s.neandertal_KF982693 \n                     -50000                      -82752 \n    H.s.neandertal_FM865411     H.s.neandertal_KY751400 \n                     -65000                     -122287 \n    H.s.neandertal_MK033602         H.s.modern_EU092846 \n                    -110450                           0 \n        H.s.modern_EU092665         H.s.modern_JQ045086 \n                          0                           0 \n        H.s.modern_DQ779927         H.s.modern_DQ779932 \n                          0                           0 \n        H.s.modern_AP008640         H.s.modern_AY495317 \n                          0                           0 \n          H.s.modern_J01415         H.s.modern_FJ236981 \n                          0                           0 \n```\n\n\n:::\n:::\n\n\n\n\nA continuación se escoge la posición de la raíz que optimiza la\nregresión entre distancia de raíz a puntas y edades de las puntas:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_nj_rtt <- rtt(mt_nj, tip.dates = fechas, objective = 'rms')\nmt_nj_rtt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPhylogenetic tree with 42 tips and 41 internal nodes.\n\nTip labels:\n  G.gorilla_D38114, P.troglodytes_JF727212, P.troglodytes_JN191207, P.troglodytes_JF727168, P.troglodytes_HM068590, P.paniscus_KX211934, ...\n\nRooted; includes branch length(s).\n```\n\n\n:::\n:::\n\n\n\n\n### Ejercicio 3\n\n*A) ¿Se corresponden bien las distancias evolutivas estimadas con las\ndataciones?*\n\nPrimero representamos el árbol filogenético teniendo en cuenta las\ndataciones:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|fig-width: 12\n#|fig-height: 7\nplot(mt_nj_rtt, align.tip.label = TRUE, show.tip.label=TRUE)\nadd.scale.bar()\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\n[CONCLUSIÓN]{.underline}: Las muestras arqueológicas deben de haber\ndejado de acumular mutaciones hace tiempo. Homo heldeibergensis es el\nque mejor se ve, su rama se queda más atrás que otros. Lo que no es\nnormal que los denisovanos tengan una rama tan larga. La función rtt\nbusca la mejor correlación entre longitudes de rama y el tiempo que ha\npasado desde que dejaron de existir. Este árbol nos dice que no se\naplicaría a la perfección el reloj molecular. Podemos desconfiar de que\nla datación sea correcta, podemos haber asignado a los denisovanos una\nedad más antigua de la que parece (igual nos hemos equivocado al\ntranscribir los datos, la media no es representativa de la edad real).\n\n*B) ¿Qué secuencias crees que se ajustan menos a su supuesta edad?*\n\nEliminamos la secuencia del gorila del dataset porque es más antigua que\nlas otras. Queremos un outgroup más cercano que P.troglodytes, pero como\nno hay nada más cercanos a los humanos nos quedamos con ellos. También\nhay pares de secuencias de neandertales que son idénticos entre ellos,\nde cada uno de esos grupos nos quedamos con una sola copia.\n\n*C) ¿Qué razones puede haber para que la edad de una secuencia no se\ncorresponda con la cantidad de cambios que ha acumulado?*\n\nLas muestras arqueologicas pueden tener errores - el método estadístico\npara corregir los errores de secuenciación y degradación del DNA puede\nque haya sido mejor en algunas muestras que en otras. Esto puede\nproducir una tendencia a alargar las ramas que pueden parecer mutaciones\npero son efectos de la degradación.\n\n## Distancias\n\nAl crear anres el objeto distancias, se puede usar para conocer la\ncantidad estimada de cambios entre los cromosomas mitocondriales humanos\ny de neandertales, por ejemplo. El objeto de clase dist es incómodo,\npero podemos obtener una simple matriz fácilmente:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistMat <- as.matrix(distancias)\n```\n:::\n\n\n\n\nAprovechando que los nombres de las secuencias tienen una estructura\ncoherente, podemos usar startsWith() para seleccionar a los humanos\nmodernos o a los neandertales, etc.:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Esto son vectores lógicos que podemos usar después para seleccionar filas\n# y columnas de la matriz de distancias.\nmodernos     <- startsWith(colnames(distMat), 'H.s.modern')\nneandertales <- startsWith(colnames(distMat), 'H.s.neandertal')\ndenisovanos  <- startsWith(colnames(distMat), 'H.s.denisova')\nchimpances   <- startsWith(colnames(distMat), 'P.troglodytes')\nbonobos      <- startsWith(colnames(distMat), 'P.paniscus')\n```\n:::\n\n\n\n\nLa distancia estimada media entre humanos y neandertales se puede\nobtener como:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(distMat[modernos, neandertales])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01214282\n```\n\n\n:::\n:::\n\n\n\n\nEn este caso la distancia estimada es de 0.01214282.\n\n### Ejercicio 4\n\n*A) Calcula las distancias medias entre todos los grupos.*\n\nComo previamente hemos calculado la distancia para cada uno de los\ngrupos, ahora calculamos la media de ambos (de dos en dos). Para ello\nutilizo la función mean().\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(distMat[modernos, denisovanos])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02250501\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[modernos, chimpances])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09104153\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[modernos, bonobos])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09239182\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[modernos, neandertales])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01214282\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[neandertales, bonobos])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09089352\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[neandertales, denisovanos])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02201398\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[neandertales, chimpances])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09041225\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[denisovanos, bonobos])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09297814\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[denisovanos, chimpances])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09129525\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(distMat[chimpances, bonobos])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04059035\n```\n\n\n:::\n:::\n\n\n\n\n*B) ¿Cuántas veces mayor es la distancia entre humanos y chimpancés que\nentre humanos y neandertales?*\n\nPara calcular esto lo hago en modo de proporción, en este caso, divido\nla distancia media entre humanos y chimpancés por la distancia media\nentre humanos y neandertales. Vemos que es 7,5 veces (aprox.) más grande\nla distancia de los primeros entre los segundos.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(distMat[modernos, chimpances])/mean(distMat[modernos, neandertales])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.497561\n```\n\n\n:::\n:::\n\n\n\n\n*C) ¿Cómo calcularías la distancia media entre dos secuencias de humanos\nmodernos?*\n\nSiguiendo la misma lógica que en los apartados anteriores:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(distMat[modernos, modernos])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003331521\n```\n\n\n:::\n:::\n\n\n\n\nEste resultado es bajo pero más alto de lo que encontraríamos en\ncromosomas nucleares.\n\nOtra alternativa presentada en clase es:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- distMat[modernos,modernos]\nmean(d[lower.tri(d)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003747961\n```\n\n\n:::\n:::\n\n\n\n\nEl resultado es similar al obtenido previamente. Esta en el mismo orden\nde magnitud.\n\nPor otra parte, atendiendo a la solución presentada en el guion de\nprácticas del Aula Virtual:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# La submatriz siguiente contiene ceros en la diagonal. Si queremos excluir\n# del cálculo de la media las distancias entre cada secuencia consigo misma,\n# habrá que tenerlo en cuenta:\ndistMat[modernos, modernos]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    H.s.modern_EU092846 H.s.modern_EU092665 H.s.modern_JQ045086\nH.s.modern_EU092846         0.000000000         0.004115877         0.005454272\nH.s.modern_EU092665         0.004115877         0.000000000         0.005393179\nH.s.modern_JQ045086         0.005454272         0.005393179         0.000000000\nH.s.modern_DQ779927         0.005392590         0.005270729         0.004724566\nH.s.modern_DQ779932         0.005513658         0.005391783         0.004906390\nH.s.modern_AP008640         0.005517618         0.005152317         0.004787395\nH.s.modern_AY495317         0.005635614         0.005148861         0.004784781\nH.s.modern_J01415           0.005453806         0.005210372         0.004785411\nH.s.modern_FJ236981         0.005331436         0.004966433         0.004481205\n                    H.s.modern_DQ779927 H.s.modern_DQ779932 H.s.modern_AP008640\nH.s.modern_EU092846         0.005392590         0.005513658         0.005517618\nH.s.modern_EU092665         0.005270729         0.005391783         0.005152317\nH.s.modern_JQ045086         0.004724566         0.004906390         0.004787395\nH.s.modern_DQ779927         0.000000000         0.001087163         0.002359394\nH.s.modern_DQ779932         0.001087163         0.000000000         0.002298600\nH.s.modern_AP008640         0.002359394         0.002298600         0.000000000\nH.s.modern_AY495317         0.002478978         0.002660427         0.001692960\nH.s.modern_J01415           0.002418729         0.002600192         0.001693182\nH.s.modern_FJ236981         0.002055212         0.002236605         0.001269395\n                    H.s.modern_AY495317 H.s.modern_J01415 H.s.modern_FJ236981\nH.s.modern_EU092846         0.005635614      0.0054538063        0.0053314359\nH.s.modern_EU092665         0.005148861      0.0052103722        0.0049664328\nH.s.modern_JQ045086         0.004784781      0.0047854113        0.0044812052\nH.s.modern_DQ779927         0.002478978      0.0024187289        0.0020552122\nH.s.modern_DQ779932         0.002660427      0.0026001920        0.0022366046\nH.s.modern_AP008640         0.001692960      0.0016931824        0.0012693954\nH.s.modern_AY495317         0.000000000      0.0010873068        0.0009058850\nH.s.modern_J01415           0.001087307      0.0000000000        0.0006642889\nH.s.modern_FJ236981         0.000905885      0.0006642889        0.0000000000\n```\n\n\n:::\n\n```{.r .cell-code}\n# Por ejemplo:\nz <- distMat[modernos, modernos]\nz[z == 0] <- NA\nmean(z, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003747961\n```\n\n\n:::\n:::\n\n\n\n\nLas distancias estimadas no son exactas. Cuanto mayor es la distancia,\nmayor es el error en la estimación. Además el modelo disponible podia no\nser el adecuado. Pero nos ayudan a estimar el tiempo transcurrido desde\nque dos linajes se separaron, si asumimos el reloj molecular. Por\nejemplo, estas distancias sugieren que los humanos modernos divergieron\nde los neandertales hace una cantidad de tiempo aproximadamente igual al\n13.3% del tiempo que nos separa de los chimpancés, que podrían ser más\nde 850000 años si del chimpancé nos separan 6.5 millones de años.\n\nEn los árboles las distancias se representan mediante la suma de las\nlongitudes que separan las hojas. Las podemos obtener con la función\ncophenetic():\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistCofen <- cophenetic(mt_nj_rooted)\n```\n:::\n\n\n\n\n### Ejercicio 5\n\n*¿Cuánto se parecen las distancias estimadas a las distancias\ncofenéticas?*\n\nPara valorar esto representamos gráficamente de la siguiente manera:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aquí usamos las matricees como vectores:\nplot(distMat, distCofen, xlab = 'Distancias F81', ylab = 'Dist. cofenéticas')\nabline(a = 0, b = 1, col = 'red', lty = 2)\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\n\n## Limpieza o filtrado del alineamiento\n\nLas distancias crudas, como número de diferencias, nos pueden informar\nde la presencia de pares de secuencias idénticas. Podríamos dejarlas,\npero algunos de los métodos que usaremos a continuación pueden generar\nerrores, por ejemplo cuando dos secuencias idénticas se supone que\npertenecen a épocas diferentes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrudas <- dist.dna(as.DNAbin(mtdna), model = 'raw')\ncrudas <- as.matrix(crudas)\nidenticas <- which(crudas == 0 & lower.tri(crudas), arr.ind = TRUE)\n# posiciones de la semimatriz inferior donde las distancias son 0:\nidenticas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        row col\nH.s.neandertal_KX198086  16  15\nH.s.neandertal_MG025540  23  15\nH.s.neandertal_MG025540  23  16\nH.s.neandertal_KX198088  21  20\nH.s.neandertal_KX198083  22  20\nH.s.neandertal_KX198082  27  20\nH.s.neandertal_KX198083  22  21\nH.s.neandertal_KX198082  27  21\nH.s.neandertal_KX198082  27  22\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrepetidas <- unique(c(identicas[, 'row'], identicas[, 'col']))\nheatmap(crudas[repetidas, repetidas], cexRow = 0.7, cexCol = 0.7)\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n\nAsí pues, las secuencias de Neandertales KX198085, KX198086 y MG025540\n(todas ellas con una edad estimada de unos 40000 años) son idénticas\nentre ellas; y las secuencias, también Neandertales FM865407, KX198082,\nKX198088 y KX198083 son idénticas entre ellas. Bueno, en realidad, la\ncomparación ignora las posiciones en las que una secuencia contiene\nambigüedades (Ns). Dejaremos sólo una de cada grupo: MG025540 y\nFM865407, que son las que menos ambigüedades tienen en la secuencia.\nComo no conocemos una función que elimine secuencias de un objeto\nphyDat, necesitamos especificar aquellas con las que nos queremos\nquedar. Podríamos usar la función subset() o bien la función \\[, tal\ncomo la aplicaríamos a una matriz. También existe una función unique(),\npero si la usamos perdemos control sobre qué representantes conservamos\nde cada grupo de secuencias idénticas.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# La exclamación (\"!\") invierte el valor lógico de lo que la sigue.\n# La función \"grepl()\" produce un vector lógico con \"TRUE\" donde los nombres\n# de las secuencias contienen alguna de esas palabras.\nmtdna37 <- mtdna[! grepl('(KX198085|KX198086|KX198082|KX198088|KX198083)',\n                         names(mtdna)), ]\nmtdna37\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n37 sequences with 16603 character and 974 different site patterns.\nThe states are a c g t \n```\n\n\n:::\n:::\n\n\n\n\nHay 37 secuencias con 16603 carácteres y 974 site patterns. Los estados\nson: a c g t.\n\n### Ejercicio 6\n\n*¿Serías capaz de crear otro conjunto de datos, mtdna28, que sólo\ncontenga secuencias del género Homo?*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtdna28 <- mtdna37[grepl('^H.', names(mtdna37)), ]\nmtdna28\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n28 sequences with 16603 character and 974 different site patterns.\nThe states are a c g t \n```\n\n\n:::\n:::\n\n\n\n\nIdentifica 28 secuencias.\n\nPor otra parte, la secuencia del gorila no nos hace falta: es demasiado\ndivergente y puede haber evolucionado a un ritmo diferente, por tanto:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtdna36 <- mtdna37[! startsWith(names(mtdna37), 'G.gorilla'),]\n```\n:::\n\n\n\n\n## Escoger el modelo de evolución molecular\n\nLas secuencias mitocondriales proporcionan suficiente información para\ndeterminar con confianza la topología del árbol que relaciona los grupos\nprincipales. Sólo algunas regiones de árbol, como la relación exacta\nentre los miembros de un mismo grupo, presentan dificultad. Para estimar\nmejor la topología y las longitudes de las ramas, debemos usar el método\nde máxima verosimilitud, para el cual sí es fundamental escoger el\nmodelo evolutivo más adecuado. Para ello usamos la funcion modelTest(),\nque devuelve un objeto de clase modelTest, que también puede usarse como\nun simple marco de datos.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelos <- modelTest(mtdna36, control = pml.control(trace = 0))\nhead(modelos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Model df    logLik      AIC AICw     AICc AICcw      BIC\n1        JC 69 -43394.16 86926.33    0 86926.91     0 87458.83\n2      JC+I 70 -42831.03 85802.05    0 85802.66     0 86342.27\n3   JC+G(4) 70 -42827.52 85795.04    0 85795.64     0 86335.25\n4 JC+G(4)+I 71 -42807.54 85757.08    0 85757.70     0 86305.01\n5       F81 72 -42567.47 85278.94    0 85279.57     0 85834.58\n6     F81+I 73 -41987.61 84121.22    0 84121.87     0 84684.58\n```\n\n\n:::\n:::\n\n\n\n\nLo que hace modelTest() es calcular la verosimilitud de cada modelo\nsobre un mismo árbol. Al hacerlo, debe optimizar los parámetros de cada\nmodelo, pero no optimiza el árbol. Sería una pérdida de tiempo no\nguardar los parámetros optimizados, que son un excelente punto de\npartida para la búsqueda del árbol más verosímil. Podemos extraer\ncualquiera de los modelos comparados con la función as.pml().\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- as.pml(modelos, 'GTR+G(4)+I')\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel: GTR+G(4)+I \nloglikelihood: -39275.11 \nunconstrained loglikelihood: -45918.42 \nProportion of invariant sites: 0.6583584 \nModel of rate heterogeneity: Discrete gamma model\nNumber of rate categories: 4 \nShape parameter: 0.9797904 \n       Rate Proportion\n1 0.0000000  0.6583584\n2 0.3890159  0.0854104\n3 1.3774432  0.0854104\n4 2.9170011  0.0854104\n5 7.0247157  0.0854104\n\nRate matrix:\n          a          c          g         t\na  0.000000  1.9682572 63.0009475  1.212889\nc  1.968257  0.0000000  0.6641116 46.671218\ng 63.000948  0.6641116  0.0000000  1.000000\nt  1.212889 46.6712184  1.0000000  0.000000\n\nBase frequencies:  \n        a         c         g         t \n0.3094827 0.3112863 0.1305929 0.2486381 \n```\n\n\n:::\n:::\n\n\n\n\nAquí se demuestra que modelos no es un simple marco de datos, sino que\ntiene escondida mucha información, incluyendo de hecho el árbol y el\nalineamiento. También podemos usar as.pml() para extraer el modelo más\nadecuado a los datos según alguno de los criterios disponibles (BIC,\nAIC, AICc). El motivo por el que el modelo más adecuado no es\nnecesariamente el más verosímil es que la verosimilitud siempre será\nmayor para un modelo más complejo (con más parámetros), porque tiene más\ngrados de libertad para ajustarse a los datos. Los criterios de\nselección penalizan los modelos con más parámetros para hacer la\ncomparación más justa. El peligro de usar un modelo con demasiados\nparámetros es el de sobreajustar el modelo, es decir, tomar el ruído\nnatural de los datos como algo que el modelo también debe explicar.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- as.pml(modelos, 'BIC')\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel: TIM2+G(4)+I \nloglikelihood: -39278.26 \nunconstrained loglikelihood: -45918.42 \nProportion of invariant sites: 0.6579267 \nModel of rate heterogeneity: Discrete gamma model\nNumber of rate categories: 4 \nShape parameter: 0.9785258 \n       Rate Proportion\n1 0.0000000 0.65792675\n2 0.3877809 0.08551831\n3 1.3745614 0.08551831\n4 2.9126763 0.08551831\n5 7.0183832 0.08551831\n\nRate matrix:\n          a         c        g         t\na  0.000000  2.033328 78.09853  2.033328\nc  2.033328  0.000000  1.00000 57.925290\ng 78.098532  1.000000  0.00000  1.000000\nt  2.033328 57.925290  1.00000  0.000000\n\nBase frequencies:  \n        a         c         g         t \n0.3094827 0.3112863 0.1305929 0.2486381 \n```\n\n\n:::\n:::\n\n\n\n\n### Ejercicio 7\n\n*¿Cuál es el mejor modelo para secuencias sólo del género Homo?*\n\nPara hacer esto he seguido el mismo planteamiento que en el caso\nanterior.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelos2 <- modelTest(mtdna28, control = pml.control(trace = 0)) \nfit2 <- as.pml(modelos2, 'BIC') \nfit2 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel: TrN+G(4)+I \nloglikelihood: -28823.51 \nunconstrained loglikelihood: -45918.42 \nProportion of invariant sites: 0.8149294 \nModel of rate heterogeneity: Discrete gamma model\nNumber of rate categories: 4 \nShape parameter: 1.003691 \n        Rate Proportion\n1  0.0000000 0.81492938\n2  0.7439846 0.04626766\n3  2.5820334 0.04626766\n4  5.4066329 0.04626766\n5 12.8807197 0.04626766\n\nRate matrix:\n       a        c      g        t\na  0.000  1.00000 53.837  1.00000\nc  1.000  0.00000  1.000 32.09634\ng 53.837  1.00000  0.000  1.00000\nt  1.000 32.09634  1.000  0.00000\n\nBase frequencies:  \n        a         c         g         t \n0.3088407 0.3122559 0.1312366 0.2476667 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- as.pml(modelos2, 'BIC') \nfit2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel: TrN+G(4)+I \nloglikelihood: -28823.51 \nunconstrained loglikelihood: -45918.42 \nProportion of invariant sites: 0.8149294 \nModel of rate heterogeneity: Discrete gamma model\nNumber of rate categories: 4 \nShape parameter: 1.003691 \n        Rate Proportion\n1  0.0000000 0.81492938\n2  0.7439846 0.04626766\n3  2.5820334 0.04626766\n4  5.4066329 0.04626766\n5 12.8807197 0.04626766\n\nRate matrix:\n       a        c      g        t\na  0.000  1.00000 53.837  1.00000\nc  1.000  0.00000  1.000 32.09634\ng 53.837  1.00000  0.000  1.00000\nt  1.000 32.09634  1.000  0.00000\n\nBase frequencies:  \n        a         c         g         t \n0.3088407 0.3122559 0.1312366 0.2476667 \n```\n\n\n:::\n:::\n\n\n\n\nEl mejor modelo en este caso es TrN+G(4)+I\n\n## Máxima verosimilitud\n\nTras seleccionar el modelo, optimizamos la topología del árbol,\nlongitudes de la ramas y otros parámetros del modelo. Usaremos la\nfunción pml_bb(), que internamente usa las funciones pml() y\noptim.pml(). Podemos modular el comportamiento de pml_bb() (cuánta\ninformación muestra del proceso, cuántas iteraciones usa, cuándo decide\nque no puede mejorar el modelo…) con los parámetros definidos mediante\npml.control(). A la función pml_bb() podemos proporcionarle el\nalineamiento (objeto de clase phyDat) y el nombre del modelo de\nevolución molecular, o bien un objeto de clase modelTest, de donde toma\nautomáticamente el alineamiento y el modelo con un valor de BIC\n(Bayesian Information Criterion) más bajo.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_ml <- pml_bb(modelos, control = pml.control(trace = 0))\n```\n:::\n\n\n\n\nEl objeto mt_ml, de clase pml, contiene el árbol (mt_ml\\$tree), además\nde los parámetros optimizados del modelo. Antes de ver el árbol,\nechémosle un vistazo al modelo ajustado, para ver cuánto se aparta del\nque habíamos ajustado con modelTest().\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_ml\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel: TIM2+G(4)+I \nloglikelihood: -39277.23 \nunconstrained loglikelihood: -45918.42 \nProportion of invariant sites: 0.6575751 \nModel of rate heterogeneity: Discrete gamma model\nNumber of rate categories: 4 \nShape parameter: 0.9767073 \n      Rate Proportion\n1 0.000000 0.65757508\n2 0.386313 0.08560623\n3 1.371503 0.08560623\n4 2.908756 0.08560623\n5 7.014820 0.08560623\n\nRate matrix:\n          a         c        g         t\na  0.000000  2.032831 77.89999  2.032831\nc  2.032831  0.000000  1.00000 57.982110\ng 77.899986  1.000000  0.00000  1.000000\nt  2.032831 57.982110  1.00000  0.000000\n\nBase frequencies:  \n        a         c         g         t \n0.3094827 0.3112863 0.1305929 0.2486381 \n```\n\n\n:::\n:::\n\n\n\n\nEl modelo recomendado es TIM2+G(4)+I\n\nPor defecto, pml_bb() usa un método de reordenación del árbol denominado\n“stochastic”, genera un árbol no enraizado y 1000 pseudo-réplicas de\nbootstrap. Al pedirle la representación gráfica, añade automáticamente\nlos valores de soporte de bootstrap y lo enraiza en el punto medio:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mt_ml, align.tip.label = TRUE, main = 'Árbol más verosímil')\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n\n\n### Ejercicio 8\n\n*A) El árbol no está enraizado. Como las secuencias no son todas de la\nmisma época, utiliza rtt() para situar la raíz en el punto más\ncompatible con la hipótesis de reloj molecular.*\n\nPara ello he seguido el mismo procedimiento que en el que se ha\nrealizado anteriormente.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfechas2 <- c(0, 0, 0, 0, -400000, 0, 0, 0, 0, -39000, -50000, -110000, -110000, -122287, -43230, -82752, -50000, -43780, -39000, -38310, -38515, -42540, -40000, -44290, -49000, -65000, -110450, 0, 0, 0, 0, 0, 0, 0, 0, 0) \nfechas2 <- setNames(fechas2, mt_ml$tip.label) \nfechas2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]       0       0       0       0 -400000       0       0       0       0\n[10]  -39000  -50000 -110000 -110000 -122287  -43230  -82752  -50000  -43780\n[19]  -39000  -38310  -38515  -42540  -40000  -44290  -49000  -65000 -110450\n[28]       0       0       0       0       0       0       0       0       0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_ml_rtt <- rtt(mt_ml$tree, tip.dates = fechas2, objective = 'rms') \nplot(mt_ml_rtt, align.tip.label = TRUE)\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n\n\n*B) ¿Podrías obtener el árbol más verosímil para el subconjunto de\nsecuencias del género Homo?*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_ml2 <- pml_bb(modelos2,                 \n                 control = pml.control(trace = 0)) \nplot(mt_ml2, align.tip.label = TRUE, main = 'Árbol más verosímil')\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n\n\n## Con datación de puntas (tip dating)\n\nEl método de máxima verosimilitud genera árboles no enraizados por\ndefecto, como consecuencia de la reversibilidad temporal. En esos\nárboles las longitudes de ramas són el número esperado de sustituciones\npor sitio, sin ninguna referencia explícita al tiempo. Pero cuando no\ntodas las secuencias son isócronas, podemos usar la información de sus\nedades para constreñir la búsqueda del árbol más verosímil. Al usar las\nedades de las secuencias, estamos asumiendo un reloj molecular: una\nrelación constante entre el tiempo y el número esperado de sustituciones\nacumuladas. Entonces, la posición de la raíz afecta la verosimilitud y\nel resultado es un árbol enraizado.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Habíamos creado el vector \"fechas\", pero incluye al gorila. \nfechas36 <- fechas[names(mtdna36)] \nmt_ml_clock <- pml_bb(modelos,                       \n                      method = 'tipdated',                       \n                      tip.dates = fechas36, rearrangement = 'NNI',                       \n                      control = pml.control(trace = 0))  \nmt_ml_clock\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel: TIM2+G(4)+I \nloglikelihood: -41234.09 \nunconstrained loglikelihood: -45918.42 \nProportion of invariant sites: 0.7646238 \nModel of rate heterogeneity: Discrete gamma model\nNumber of rate categories: 4 \nShape parameter: 1.092121 \n          Rate Proportion\n1 0.000000e+00 0.76462377\n2 7.627412e-09 0.05884406\n3 2.474842e-08 0.05884406\n4 4.989794e-08 0.05884406\n5 1.146144e-07 0.05884406\n\nRate: 1.15857e-08 \n\nRate matrix:\n          a         c        g         t\na  0.000000  2.319011 57.89519  2.319011\nc  2.319011  0.000000  1.00000 47.953244\ng 57.895191  1.000000  0.00000  1.000000\nt  2.319011 47.953244  1.00000  0.000000\n\nBase frequencies:  \n        a         c         g         t \n0.3094827 0.3112863 0.1305929 0.2486381 \n\nRate: 1.15857e-08 \n```\n\n\n:::\n:::\n\n\n\n\nEn este caso el modelo TIM2+G(4)+I.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mt_ml_clock, align.tip.label = TRUE)\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n\n\n### Ejercicio 9\n\n*A)¿Cuál es la tasa de mutación global estimada?*\n\nA partir de los datos obtenidos anteriores, concluyo que la tasa de\nmutación es de 1.15857e-08.\n\n*B) ¿En qué unidades está expresada?*\n\nCorresponde al número de mutaciones por sitio, por lo que estas son las\nunidades.\n\n*C) ¿Cuánto tiempo dice el árbol que divergimos de los chimpancés?\n(Puedes usar la función cophenetic(), puesto que en el árbol datado las\nlongitudes de las ramas están en años).*\n\nHe consultado la ayuda de la función cophenetic () y luego he procedido\ntal y como se ha hecho anteriormente en esta práctica. Esta función\ncalcula la distancia entre dos ramas del árbol (como se ha visto antes,\nen los árboles las distancias se representan mediante la suma de las\nlongitudes que separan las hojas). En mi caso, he visualizado en la\nconsola de R studio la distancia entre humanos-chimpancés que es de\n[1804164,5 años]{.underline}.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistCofen2 <- cophenetic(mt_ml_clock$tree)\n```\n:::\n\n\n\n\n## Estimación de edades\n\nLas edades de las secuencias aportan información sobre el reloj\nmolecular en la medida en que se echen de menos las mutaciones que\ndejaron de acumularse en las secuencias arcaicas. Esta información puede\nser muy útil en filogenias de virus de ARN muestreados a lo largo de los\naños. Pero en una filogenia de millones de años, la poca información de\nlas puntas no es suficiente para datar con exactitud las divergencias\nantiguas. Hay otras estrategias. Podríamos fijar una tasa de mutación\nconocida y estimar sólo los otros parámetros. Alternativamente, podemos\ndar la fecha de algún nodo interno para ayudar a calibrar el reloj. *Por\nejemplo, supondremos que el ancestro común más reciente entre humanos y\nchimpancés vivió hace 6.5 millones de años.*\n\nEsta información se la proporcionamos a la función estimate.dates()\nmediante un vector de fechas o edades de las secuencias que incluya no\nsólo las hojas del árbol sino también los nodos internos, o al menos\naquellos de los que conocemos la edad. El vector debe tener tantos\ncomponentes como nodos internos y hojas tiene el árbol, con valores NA\nen las edades desconocidas. Para saber en qué orden están numerados los\nnodos, podemos ejecutar lo siguiente:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_ml_rtt <- rtt(mt_ml$tree, fechas36) \nplot(mt_ml_rtt, align.tip.label = TRUE) \nnodelabels()\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n\n\nComo suele suceder, la raíz (en los árboles enraizados) es el nodo que\nsigue a las hojas, es decir el 37, porque los 36 primeros números son\nlas puntas.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfechasNodos <- c(fechas36, -6500000, rep(NA, 34)) \nfechasEstimadas <- estimate.dates(mt_ml_rtt, fechasNodos) \ntasaEstimada <- estimate.mu(mt_ml_rtt, fechasNodos) \n# Creamos una copia del árbol... \nmt_ml_años <- mt_ml_rtt \n# ...y actualizamos las longitudes de sus ramas como la resta # entre las fechas de los nodos que conectan: \nmt_ml_años$edge.length <- fechasEstimadas[mt_ml_años$edge[,2]] -                           \n  fechasEstimadas[mt_ml_años$edge[,1]] \nplot(mt_ml_años) \naxisPhylo()\n```\n\n::: {.cell-output-display}\n![](P9_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntasaEstimada\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.314216e-08\n```\n\n\n:::\n:::\n\n\n\n\nLa tasa estimada es de 1.31428e-08.\n\nAl forzar que la raíz esté a unos 6.5 millones de años, la tasa de\nmutación estimada disminuye. Es habitual que las tasas parezcan\ndiferentes a diferentes profundidades del árbol, o entre linajes\ndiferentes.\n",
    "supporting": [
      "P9_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}